# Script Python - Jupyter - BANCO DE DISPENSA - CONVERS√ÉO - TXT PARA HDF5 
# 20/09/21 por Mikael Lemos - V1.0

## Carregando as bibliotecas

In [1]:
import os
import openpyxl
import black 
import numpy as np
import pandas as pd
import pypolars as pl
import pyreadstat
from datetime import datetime, date, time, timezone
import pyflowchart
import vaex
from pathlib import Path
import h5py

WARNING!
py-polars was renamed to polars, please install polars!
https://pypi.org/project/polars/

## Carregando dados/indicar pasta

In [2]:
os.chdir("C:/Users/lemos/Downloads/AMA/produtos_opas/2021/produto2/dispensa")

## Ler arquivos TXT como CSV - Dataframe

In [4]:
tb_dispensas_esquemas_udm = pd.read_csv('tb_dispensas_esquemas_udm.txt', 
                       sep='\t',
                       error_bad_lines=False, 
                       header=None)

b'Skipping line 652503: expected 67 fields, saw 70\nSkipping line 654481: expected 67 fields, saw 70\n'
b'Skipping line 657594: expected 67 fields, saw 70\n'
b'Skipping line 2262087: expected 67 fields, saw 68\n'
b'Skipping line 3001159: expected 67 fields, saw 70\n'
b'Skipping line 3339283: expected 67 fields, saw 70\n'
b'Skipping line 3348183: expected 67 fields, saw 70\n'
b'Skipping line 3549377: expected 67 fields, saw 68\n'
b'Skipping line 4124147: expected 67 fields, saw 68\n'
b'Skipping line 5083068: expected 67 fields, saw 70\n'
b'Skipping line 5239759: expected 67 fields, saw 70\n'
b'Skipping line 5297084: expected 67 fields, saw 70\n'
b'Skipping line 5313448: expected 67 fields, saw 70\n'
b'Skipping line 6170689: expected 67 fields, saw 68\n'
b'Skipping line 6534445: expected 67 fields, saw 70\n'
b'Skipping line 6687323: expected 67 fields, saw 79\n'
b'Skipping line 7358241: expected 67 fields, saw 70\n'
b'Skipping line 7435118: expected 67 fields, saw 70\n'
b'Skipping line 7878121: expected 67 fields, saw 68\n'
b'Skipping line 8009574: expected 67 fields, saw 70\n'
b'Skipping line 8828208: expected 67 fields, saw 68\n'
b'Skipping line 8859094: expected 67 fields, saw 70\n'
b'Skipping line 9065023: expected 67 fields, saw 70\n'
b'Skipping line 9638325: expected 67 fields, saw 70\n'
b'Skipping line 9826146: expected 67 fields, saw 70\n'
b'Skipping line 9943096: expected 67 fields, saw 70\n'
b'Skipping line 10007148: expected 67 fields, saw 68\n'
b'Skipping line 10181028: expected 67 fields, saw 70\n'
b'Skipping line 10975722: expected 67 fields, saw 68\n'
b'Skipping line 12121513: expected 67 fields, saw 68\n'
b'Skipping line 12698403: expected 67 fields, saw 68\n'
b'Skipping line 12770514: expected 67 fields, saw 68\n'
b'Skipping line 13349710: expected 67 fields, saw 70\n'
b'Skipping line 13708421: expected 67 fields, saw 68\n'
b'Skipping line 14290654: expected 67 fields, saw 68\n'
b'Skipping line 14436862: expected 67 fields, saw 70\n'
b'Skipping line 15121956: expected 67 fields, saw 68\n'
b'Skipping line 15154160: expected 67 fields, saw 70\n'
b'Skipping line 15414586: expected 67 fields, saw 68\n'
b'Skipping line 15467354: expected 67 fields, saw 68\n'
b'Skipping line 15540009: expected 67 fields, saw 74\n'
b'Skipping line 15999676: expected 67 fields, saw 70\n'
b'Skipping line 16273674: expected 67 fields, saw 70\n'
C:\Users\lemos\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (1,2,8,10,20,21,22,23,27,31,34,35,37,38,39,44) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

## Incluir nomes das colunas

In [5]:
tb_dispensas_esquemas_udm = tb_dispensas_esquemas_udm.set_axis(["codigo_paciente","cod_pac_final", "codigo_udm","num_solicit","cod_ibge_udm","categoria_disp","st_profilaxia","idade","categoria_crianca","categoria_usuario","periodo_gest","validade_form","peso_kg","st_tb","st_hbv","st_hcv","motivo_mudanca_tratamento","st_mutacao_drv","st_falha_3tc","medicamento_mud_1","medicamento_mud_2","medicamento_mud_3","medicamento_mud_4","medicamento_mud_5","just_outros","st_arv_restrito","st_situacao_especial","nu_protocolo","ultima_carga_viral_digitada_siclom","data_exame_cv","st_exame_cv","data_exame_cd4","ultimo_cd4_digitado_siclom","perc_cd4","st_exame_cd4","st_dtg","st_ajuste_tdf","st_atz","st_esquema_dtg_dobro","data_desfecho_gestacao","data_dispensa","esquema","esquema_forma","duracao","cd_crm","uf_crm","data_PriDisp","PriDisp","UltDisp_2009","UltDisp_2010","UltDisp_2011","UltDisp_2012","UltDisp_2013","UltDisp_2014","UltDisp_2015","UltDisp_2016","UltDisp_2017","UltDisp_2018","UltDisp_2019","UltDisp_2020","UltDisp_2021","UltDispVida","data_dispensa_anterior","data_dispensa_posterior","data_ultima_dispensa","duracao_dispensa_anterior","duracao_dispensa_posterior"]  , axis=1)

In [6]:
 #names=["codigo_paciente","cod_pac_final", "codigo_udm","num_solicit","cod_ibge_udm","categoria_disp","st_profilaxia","idade","categoria_crianca","categoria_usuario","periodo_gest","validade_form","peso_kg","st_tb","st_hbv","st_hcv","motivo_mudanca_tratamento","st_mutacao_drv","st_falha_3tc","medicamento_mud_1","medicamento_mud_2","medicamento_mud_3","medicamento_mud_4","medicamento_mud_5","just_outros","st_arv_restrito","st_situacao_especial","nu_protocolo","ultima_carga_viral_digitada_siclom","data_exame_cv","st_exame_cv","data_exame_cd4","ultimo_cd4_digitado_siclom","perc_cd4","st_exame_cd4","st_dtg","st_ajuste_tdf","st_atz","st_esquema_dtg_dobro","data_desfecho_gestacao","data_dispensa","esquema","esquema_forma","duracao","cd_crm","uf_crm","data_PriDisp","PriDisp","UltDisp_2009","UltDisp_2010","UltDisp_2011","UltDisp_2012","UltDisp_2013","UltDisp_2014","UltDisp_2015","UltDisp_2016","UltDisp_2017","UltDisp_2018","UltDisp_2019","UltDisp_2020","UltDisp_2021","UltDispVida","data_dispensa_anterior","data_dispensa_posterior","data_ultima_dispensa","duracao_dispensa_anterior","duracao_dispensa_posterior"]

## Conferir tabela

In [7]:
tb_dispensas_esquemas_udm.head()

,codigo_paciente,cod_pac_final,codigo_udm,num_solicit,cod_ibge_udm,categoria_disp,st_profilaxia,idade,categoria_crianca,categoria_usuario,...,UltDisp_2018,UltDisp_2019,UltDisp_2020,UltDisp_2021,UltDispVida,data_dispensa_anterior,data_dispensa_posterior,data_ultima_dispensa,duracao_dispensa_anterior,duracao_dispensa_posterior
0,70,70,044,131589,3304557.0,O,1,66.0,NaN,HIV/AIDS - Adulto,...,0,0,0,0,0,2018-05-11 11:22:20.000,2021-08-20 09:50:42.000,2021-08-20 09:50:42.000,30.0,30.0
1,70,70,044,128194,3304557.0,O,1,66.0,NaN,HIV/AIDS - Adulto,...,0,0,0,0,0,2018-02-06 15:32:59.000,2021-08-20 09:50:42.000,2021-08-20 09:50:42.000,30.0,30.0
2,875,875,351,7283,2304400.0,O,1,63.0,NaN,HIV/AIDS - Adulto,...,0,0,0,0,0,2018-08-21 15:19:28.000,2019-02-19 09:38:24.000,2019-02-19 09:38:24.000,30.0,60.0
3,875,875,351,7570,2304400.0,O,1,63.0,NaN,HIV/AIDS - Adulto,...,0,0,0,0,0,2018-09-18 11:36:00.000,2019-02-19 09:38:24.000,2019-02-19 09:38:24.000,30.0,60.0
4,875,875,351,7716,2304400.0,O,1,63.0,NaN,HIV/AIDS - Adulto,...,0,0,0,0,0,2018-10-20 14:29:57.000,2019-02-19 09:38:24.000,2019-02-19 09:38:24.000,30.0,60.0

## Verificar uso de mem√≥ria - passo opcional

In [8]:
tb_dispensas_esquemas_udm.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16599052 entries, 0 to 16599051
Data columns (total 67 columns):
 #   Column                              Dtype
---  ------                              -----
 0   codigo_paciente                     int64
 1   cod_pac_final                       object
 2   codigo_udm                          object
 3   num_solicit                         int64
 4   cod_ibge_udm                        float64
 5   categoria_disp                      object
 6   st_profilaxia                       int64
 7   idade                               float64
 8   categoria_crianca                   object
 9   categoria_usuario                   object
 10  periodo_gest                        object
 11  validade_form                       float64
 12  peso_kg                             float64
 13  st_tb                               object
 14  st_hbv                              object
 15  st_hcv                              object
 16  motivo_mudanca_tratamento           object
 17  st_mutacao_drv                      float64
 18  st_falha_3tc                        float64
 19  medicamento_mud_1                   object
 20  medicamento_mud_2                   object
 21  medicamento_mud_3                   object
 22  medicamento_mud_4                   object
 23  medicamento_mud_5                   object
 24  just_outros                         object
 25  st_arv_restrito                     object
 26  st_situacao_especial                object
 27  nu_protocolo                        object
 28  ultima_carga_viral_digitada_siclom  object
 29  data_exame_cv                       object
 30  st_exame_cv                         object
 31  data_exame_cd4                      object
 32  ultimo_cd4_digitado_siclom          float64
 33  perc_cd4                            float64
 34  st_exame_cd4                        object
 35  st_dtg                              object
 36  st_ajuste_tdf                       object
 37  st_atz                              object
 38  st_esquema_dtg_dobro                object
 39  data_desfecho_gestacao              object
 40  data_dispensa                       object
 41  esquema                             object
 42  esquema_forma                       object
 43  duracao                             int64
 44  cd_crm                              object
 45  uf_crm                              object
 46  data_PriDisp                        object
 47  PriDisp                             int64
 48  UltDisp_2009                        int64
 49  UltDisp_2010                        int64
 50  UltDisp_2011                        int64
 51  UltDisp_2012                        int64
 52  UltDisp_2013                        int64
 53  UltDisp_2014                        int64
 54  UltDisp_2015                        int64
 55  UltDisp_2016                        int64
 56  UltDisp_2017                        int64
 57  UltDisp_2018                        int64
 58  UltDisp_2019                        int64
 59  UltDisp_2020                        int64
 60  UltDisp_2021                        int64
 61  UltDispVida                         int64
 62  data_dispensa_anterior              object
 63  data_dispensa_posterior             object
 64  data_ultima_dispensa                object
 65  duracao_dispensa_anterior           float64
 66  duracao_dispensa_posterior          float64
dtypes: float64(10), int64(19), object(38)
memory usage: 34.9 GB

## Salvar como arquivo hdf5 (formato bin√°rio)

In [9]:
vaex_tb_dispensas_esquemas_udm = vaex.from_pandas(tb_dispensas_esquemas_udm, copy_index=False)

In [10]:
vaex_tb_dispensas_esquemas_udm.export('tb_dispensas_esquemas_udm.hdf5')

ERROR:MainThread:vaex.hdf5.writer:error creating dataset for 'cod_pac_final', with type object
Traceback (most recent call last):
  File "C:\Users\lemos\anaconda3\lib\site-packages\vaex\hdf5\writer.py", line 70, in layout
    self.column_writers[name] = ColumnWriterPrimitive(self.columns, name, dtypes[name], shape, has_null[name], self.byteorder)
  File "C:\Users\lemos\anaconda3\lib\site-packages\vaex\hdf5\writer.py", line 147, in __init__
    self.array = self.h5group.require_dataset('data', shape=shape, dtype=dtype.numpy.newbyteorder(byteorder))
  File "C:\Users\lemos\anaconda3\lib\site-packages\h5py\_hl\group.py", line 191, in require_dataset
    return self.create_dataset(name, *(shape, dtype), **kwds)
  File "C:\Users\lemos\anaconda3\lib\site-packages\h5py\_hl\group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "C:\Users\lemos\anaconda3\lib\site-packages\h5py\_hl\dataset.py", line 118, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py\h5t.pyx", line 1634, in h5py.h5t.py_create
  File "h5py\h5t.pyx", line 1656, in h5py.h5t.py_create
  File "h5py\h5t.pyx", line 1711, in h5py.h5t.py_create
TypeError: Object dtype dtype('O') has no native HDF5 equivalent
ERROR:MainThread:vaex.hdf5.writer:error creating dataset for 'codigo_udm', with type object
Traceback (most recent call last):
  File "C:\Users\lemos\anaconda3\lib\site-packages\vaex\hdf5\writer.py", line 70, in layout
    self.column_writers[name] = ColumnWriterPrimitive(self.columns, name, dtypes[name], shape, has_null[name], self.byteorder)
  File "C:\Users\lemos\anaconda3\lib\site-packages\vaex\hdf5\writer.py", line 147, in __init__
    self.array = self.h5group.require_dataset('data', shape=shape, dtype=dtype.numpy.newbyteorder(byteorder))
  File "C:\Users\lemos\anaconda3\lib\site-packages\h5py\_hl\group.py", line 191, in require_dataset
    return self.create_dataset(name, *(shape, dtype), **kwds)
  File "C:\Users\lemos\anaconda3\lib\site-packages\h5py\_hl\group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "C:\Users\lemos\anaconda3\lib\site-packages\h5py\_hl\dataset.py", line 118, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py\h5t.pyx", line 1634, in h5py.h5t.py_create
  File "h5py\h5t.pyx", line 1656, in h5py.h5t.py_create
  File "h5py\h5t.pyx", line 1711, in h5py.h5t.py_create
TypeError: Object dtype dtype('O') has no native HDF5 equivalent
ERROR:MainThread:vaex.hdf5.writer:error creating dataset for 'periodo_gest', with type object
Traceback (most recent call last):
  File "C:\Users\lemos\anaconda3\lib\site-packages\vaex\hdf5\writer.py", line 70, in layout
    self.column_writers[name] = ColumnWriterPrimitive(self.columns, name, dtypes[name], shape, has_null[name], self.byteorder)
  File "C:\Users\lemos\anaconda3\lib\site-packages\vaex\hdf5\writer.py", line 147, in __init__
    self.array = self.h5group.require_dataset('data', shape=shape, dtype=dtype.numpy.newbyteorder(byteorder))
  File "C:\Users\lemos\anaconda3\lib\site-packages\h5py\_hl\group.py", line 191, in require_dataset
    return self.create_dataset(name, *(shape, dtype), **kwds)
  File "C:\Users\lemos\anaconda3\lib\site-packages\h5py\_hl\group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "C:\Users\lemos\anaconda3\lib\site-packages\h5py\_hl\dataset.py", line 118, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py\h5t.pyx", line 1634, in h5py.h5t.py_create
  File "h5py\h5t.pyx", line 1656, in h5py.h5t.py_create
  File "h5py\h5t.pyx", line 1711, in h5py.h5t.py_create
TypeError: Object dtype dtype('O') has no native HDF5 equivalent
ERROR:MainThread:vaex.hdf5.writer:error creating dataset for 'nu_protocolo', with type object
Traceback (most recent call last):
  File "C:\Users\lemos\anaconda3\lib\site-packages\vaex\hdf5\writer.py", line 70, in layout
    self.column_writers[name] = ColumnWriterPrimitive(self.columns, name, dtypes[name], shape, has_null[name], self.byteorder)
  File "C:\Users\lemos\anaconda3\lib\site-packages\vaex\hdf5\writer.py", line 147, in __init__
    self.array = self.h5group.require_dataset('data', shape=shape, dtype=dtype.numpy.newbyteorder(byteorder))
  File "C:\Users\lemos\anaconda3\lib\site-packages\h5py\_hl\group.py", line 191, in require_dataset
    return self.create_dataset(name, *(shape, dtype), **kwds)
  File "C:\Users\lemos\anaconda3\lib\site-packages\h5py\_hl\group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "C:\Users\lemos\anaconda3\lib\site-packages\h5py\_hl\dataset.py", line 118, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py\h5t.pyx", line 1634, in h5py.h5t.py_create
  File "h5py\h5t.pyx", line 1656, in h5py.h5t.py_create
  File "h5py\h5t.pyx", line 1711, in h5py.h5t.py_create
TypeError: Object dtype dtype('O') has no native HDF5 equivalent
ERROR:MainThread:vaex.hdf5.writer:error creating dataset for 'cd_crm', with type object
Traceback (most recent call last):
  File "C:\Users\lemos\anaconda3\lib\site-packages\vaex\hdf5\writer.py", line 70, in layout
    self.column_writers[name] = ColumnWriterPrimitive(self.columns, name, dtypes[name], shape, has_null[name], self.byteorder)
  File "C:\Users\lemos\anaconda3\lib\site-packages\vaex\hdf5\writer.py", line 147, in __init__
    self.array = self.h5group.require_dataset('data', shape=shape, dtype=dtype.numpy.newbyteorder(byteorder))
  File "C:\Users\lemos\anaconda3\lib\site-packages\h5py\_hl\group.py", line 191, in require_dataset
    return self.create_dataset(name, *(shape, dtype), **kwds)
  File "C:\Users\lemos\anaconda3\lib\site-packages\h5py\_hl\group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "C:\Users\lemos\anaconda3\lib\site-packages\h5py\_hl\dataset.py", line 118, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
  File "h5py\h5t.pyx", line 1634, in h5py.h5t.py_create
  File "h5py\h5t.pyx", line 1656, in h5py.h5t.py_create
  File "h5py\h5t.pyx", line 1711, in h5py.h5t.py_create
TypeError: Object dtype dtype('O') has no native HDF5 equivalent

## Ler arquivos TXT como CSV - Dataframe - CD4 - tb_cd4_consolidado.txt

In [2]:
tb_cd4_consolidado = pd.read_csv('tb_cd4_consolidado.txt', 
                       sep='\t',
                       error_bad_lines=False, 
                       header=None)

C:\Users\lemos\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3331: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

## Incluir nome das colunas

In [3]:
names2=["cod_pac","cod_pac_final", "cod_ibge_udm","paciente_gestante","motivo_exame","cd_ibge_coletora","cd_ibge_executora","data_solicitacao","data_hora_coleta","data_do_resultado","condicoes_chegada","contagem_cd4","perc_cd4","contagem_cd8","perc_cd8","sintomatico","dt_primeira_dispensa","dt_ultimo_exame","HIV","PriCD4","UltCD4_2009","UltCD4_2010","UltCD4_2011","UltCD4_2012","UltCD4_2013","UltCD4_2014","UltCD4_2015","UltCD4_2016","UltCD4_2017","UltCD4_2018","UltCD4_2019","UltCD4_2020","UltCD4_2021","UltCD4_antesTARV","tipo_unidade"]

In [4]:
tb_cd4_consolidado = tb_cd4_consolidado.set_axis([names2]  , axis=1)

In [5]:
tb_cd4_consolidado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9093649 entries, 0 to 9093648
Data columns (total 35 columns):
 #   Column                   Dtype
---  ------                   -----
 0   (cod_pac,)               int64
 1   (cod_pac_final,)         int64
 2   (cod_ibge_udm,)          float64
 3   (paciente_gestante,)     float64
 4   (motivo_exame,)          float64
 5   (cd_ibge_coletora,)      float64
 6   (cd_ibge_executora,)     int64
 7   (data_solicitacao,)      object
 8   (data_hora_coleta,)      object
 9   (data_do_resultado,)     object
 10  (condicoes_chegada,)     int64
 11  (contagem_cd4,)          float64
 12  (perc_cd4,)              float64
 13  (contagem_cd8,)          float64
 14  (perc_cd8,)              float64
 15  (sintomatico,)           object
 16  (dt_primeira_dispensa,)  object
 17  (dt_ultimo_exame,)       object
 18  (HIV,)                   int64
 19  (PriCD4,)                int64
 20  (UltCD4_2009,)           int64
 21  (UltCD4_2010,)           int64
 22  (UltCD4_2011,)           int64
 23  (UltCD4_2012,)           int64
 24  (UltCD4_2013,)           int64
 25  (UltCD4_2014,)           int64
 26  (UltCD4_2015,)           int64
 27  (UltCD4_2016,)           int64
 28  (UltCD4_2017,)           int64
 29  (UltCD4_2018,)           int64
 30  (UltCD4_2019,)           int64
 31  (UltCD4_2020,)           int64
 32  (UltCD4_2021,)           int64
 33  (UltCD4_antesTARV,)      int64
 34  (tipo_unidade,)          object
dtypes: float64(8), int64(20), object(7)
memory usage: 2.4+ GB

In [6]:
tb_cd4_consolidado['UltCD4_2009'] = tb_cd4_consolidado['UltCD4_2009'].fillna(0).astype(np.int64)
tb_cd4_consolidado['UltCD4_2010'] = tb_cd4_consolidado['UltCD4_2010'].fillna(0).astype(np.int64)
tb_cd4_consolidado['UltCD4_2011'] = tb_cd4_consolidado['UltCD4_2011'].fillna(0).astype(np.int64)
tb_cd4_consolidado['UltCD4_2012'] = tb_cd4_consolidado['UltCD4_2012'].fillna(0).astype(np.int64)
tb_cd4_consolidado['UltCD4_2013'] = tb_cd4_consolidado['UltCD4_2013'].fillna(0).astype(np.int64)
tb_cd4_consolidado['UltCD4_2014'] = tb_cd4_consolidado['UltCD4_2014'].fillna(0).astype(np.int64)
tb_cd4_consolidado['UltCD4_2015'] = tb_cd4_consolidado['UltCD4_2015'].fillna(0).astype(np.int64)
tb_cd4_consolidado['UltCD4_2016'] = tb_cd4_consolidado['UltCD4_2016'].fillna(0).astype(np.int64)
tb_cd4_consolidado['UltCD4_2017'] = tb_cd4_consolidado['UltCD4_2017'].fillna(0).astype(np.int64)
tb_cd4_consolidado['UltCD4_2018'] = tb_cd4_consolidado['UltCD4_2018'].fillna(0).astype(np.int64)
tb_cd4_consolidado['UltCD4_2019'] = tb_cd4_consolidado['UltCD4_2019'].fillna(0).astype(np.int64)
tb_cd4_consolidado['UltCD4_2020'] = tb_cd4_consolidado['UltCD4_2020'].fillna(0).astype(np.int64)
tb_cd4_consolidado['UltCD4_2021'] = tb_cd4_consolidado['UltCD4_2021'].fillna(0).astype(np.int64)

In [8]:
tb_cd4_consolidado

,cod_pac,cod_pac_final,cod_ibge_udm,paciente_gestante,motivo_exame,cd_ibge_coletora,cd_ibge_executora,data_solicitacao,data_hora_coleta,data_do_resultado,...,UltCD4_2014,UltCD4_2015,UltCD4_2016,UltCD4_2017,UltCD4_2018,UltCD4_2019,UltCD4_2020,UltCD4_2021,UltCD4_antesTARV,tipo_unidade
0,99971268,58500928,4314407.0,2.0,2.0,4314407.0,4315602,2002-05-14 00:00:00.000,2002-05-15 07:30:00.000,2002-06-11 10:01:43.153,...,0,0,0,0,0,0,0,0,1,SAE
1,99969034,99969034,4314407.0,2.0,1.0,4314407.0,4315602,2010-06-14 00:00:00.000,2010-06-16 09:15:00.000,2010-06-24 16:21:40.340,...,0,0,0,0,0,0,0,0,0,SAE
2,99971268,58500928,4314407.0,2.0,1.0,4314407.0,4315602,2003-02-25 00:00:00.000,2003-02-26 09:00:00.000,2003-03-17 16:44:36.983,...,0,0,0,0,0,0,0,0,1,SAE
3,99968955,99968955,4314407.0,2.0,2.0,4314407.0,4315602,2003-02-14 00:00:00.000,2003-03-12 08:50:00.000,2003-04-02 16:39:51.530,...,0,0,0,0,0,0,0,0,0,SAE
4,7877,7877,4202909.0,2.0,2.0,4202909.0,4205407,2002-01-30 00:00:00.000,2002-01-30 08:00:00.000,2002-02-08 08:40:30.427,...,0,0,0,0,0,0,0,0,0,SAE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9093644,239455,239455,3550308.0,3.0,2.0,3550308.0,3550308,2021-07-07 00:00:00.000,2021-07-07 08:00:00.000,2021-07-12 09:19:47.000,...,0,0,0,0,0,0,0,1,1,AME
9093645,99052380,99052380,4205407.0,NaN,2.0,4205407.0,4205407,2021-07-28 00:00:00.000,2021-07-28 09:00:00.000,2021-08-05 13:54:16.000,...,0,0,0,0,0,0,0,1,1,NaN
9093646,337021,337021,3550308.0,NaN,2.0,3550308.0,3550308,2021-08-05 00:00:00.000,2021-08-05 07:00:00.000,2021-08-05 16:33:54.000,...,0,0,0,0,0,0,0,1,1,HOSP
9093647,99804142,99804142,4110078.0,NaN,2.0,4110078.0,4113700,NaN,2019-03-14 07:00:00.000,2019-03-15 11:00:06.000,...,0,0,0,0,0,1,0,0,1,NaN
9093648,162949,162949,4110078.0,1.0,NaN,4110078.0,4113700,NaN,2019-08-12 07:00:00.000,2019-08-14 12:02:12.000,...,0,0,0,0,0,1,0,0,1,NaN

## Salvar como arquivo hdf5 (formato bin√°rio)

In [9]:
vaex_tb_cd4_consolidado = vaex.from_pandas(tb_cd4_consolidado, copy_index=True)

In [ ]:
vaex_tb_cd4_consolidado.export('tb_cd4_consolidado.hdf5')

## Ler arquivos TXT como CSV - Dataframe - CD4 - tb_carga_viral_consolidado.txt

In [2]:
tb_carga_viral_consolidado = pd.read_csv('tb_cd4_consolidado.txt', 
                       sep='\t',
                       error_bad_lines=False, 
                       header=None)

C:\Users\lemos\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3331: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

## Incluir nome nas colunas

In [4]:
names3=["cod_pac","cod_pac_final", "cod_ibge_udm","paciente_gestante","motivo_exame","cd_ibge_coletora","cd_ibge_executora","data_solicitacao","data_hora_coleta","data_do_resultado","condicoes_chegada","contagem_cd4","perc_cd4","contagem_cd8","perc_cd8","sintomatico","dt_primeira_dispensa","dt_ultimo_exame","HIV","PriCV","UltCV_2009","UltCV_2010","UltCV_2011","UltCV_2012","UltCV_2013","UltCV_2014","UltCV_2015","UltCV_2016","UltCV_2017","UltCV_2018","UltCV_2019","UltCV_2020","UltCV_2021","UltCD4_antesTARV","tipo_unidade"]

In [5]:
tb_carga_viral_consolidado = tb_carga_viral_consolidado.set_axis([names3]  , axis=1)

In [6]:
pd.set_option('display.max_columns', None)
tb_carga_viral_consolidado.head()

,cod_pac,cod_pac_final,cod_ibge_udm,paciente_gestante,motivo_exame,cd_ibge_coletora,cd_ibge_executora,data_solicitacao,data_hora_coleta,data_do_resultado,condicoes_chegada,contagem_cd4,perc_cd4,contagem_cd8,perc_cd8,sintomatico,dt_primeira_dispensa,dt_ultimo_exame,HIV,PriCV,UltCV_2009,UltCV_2010,UltCV_2011,UltCV_2012,UltCV_2013,UltCV_2014,UltCV_2015,UltCV_2016,UltCV_2017,UltCV_2018,UltCV_2019,UltCV_2020,UltCV_2021,UltCD4_antesTARV,tipo_unidade
0,99971268,58500928,4314407.0,2.0,2.0,4314407.0,4315602,2002-05-14 00:00:00.000,2002-05-15 07:30:00.000,2002-06-11 10:01:43.153,1,394.0,NaN,434.0,NaN,A,NaN,2003-02-26 09:00:00.000,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,SAE
1,99969034,99969034,4314407.0,2.0,1.0,4314407.0,4315602,2010-06-14 00:00:00.000,2010-06-16 09:15:00.000,2010-06-24 16:21:40.340,1,380.0,13.81,1975.0,71.75,A,2014-04-14 16:00:56.000,2015-11-23 08:00:00.000,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,SAE
2,99971268,58500928,4314407.0,2.0,1.0,4314407.0,4315602,2003-02-25 00:00:00.000,2003-02-26 09:00:00.000,2003-03-17 16:44:36.983,1,88.0,NaN,310.0,NaN,S,NaN,2003-02-26 09:00:00.000,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,SAE
3,99968955,99968955,4314407.0,2.0,2.0,4314407.0,4315602,2003-02-14 00:00:00.000,2003-03-12 08:50:00.000,2003-04-02 16:39:51.530,1,696.0,NaN,1943.0,NaN,A,2008-05-26 00:00:00.000,2016-11-09 08:00:00.000,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,SAE
4,7877,7877,4202909.0,2.0,2.0,4202909.0,4205407,2002-01-30 00:00:00.000,2002-01-30 08:00:00.000,2002-02-08 08:40:30.427,1,851.0,44.58,597.0,31.27,A,2006-10-25 00:00:00.000,2011-04-04 14:00:00.000,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,SAE

In [7]:
tb_carga_viral_consolidado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9093649 entries, 0 to 9093648
Data columns (total 35 columns):
 #   Column                   Dtype
---  ------                   -----
 0   (cod_pac,)               int64
 1   (cod_pac_final,)         int64
 2   (cod_ibge_udm,)          float64
 3   (paciente_gestante,)     float64
 4   (motivo_exame,)          float64
 5   (cd_ibge_coletora,)      float64
 6   (cd_ibge_executora,)     int64
 7   (data_solicitacao,)      object
 8   (data_hora_coleta,)      object
 9   (data_do_resultado,)     object
 10  (condicoes_chegada,)     int64
 11  (contagem_cd4,)          float64
 12  (perc_cd4,)              float64
 13  (contagem_cd8,)          float64
 14  (perc_cd8,)              float64
 15  (sintomatico,)           object
 16  (dt_primeira_dispensa,)  object
 17  (dt_ultimo_exame,)       object
 18  (HIV,)                   int64
 19  (PriCV,)                 int64
 20  (UltCV_2009,)            int64
 21  (UltCV_2010,)            int64
 22  (UltCV_2011,)            int64
 23  (UltCV_2012,)            int64
 24  (UltCV_2013,)            int64
 25  (UltCV_2014,)            int64
 26  (UltCV_2015,)            int64
 27  (UltCV_2016,)            int64
 28  (UltCV_2017,)            int64
 29  (UltCV_2018,)            int64
 30  (UltCV_2019,)            int64
 31  (UltCV_2020,)            int64
 32  (UltCV_2021,)            int64
 33  (UltCD4_antesTARV,)      int64
 34  (tipo_unidade,)          object
dtypes: float64(8), int64(20), object(7)
memory usage: 2.4+ GB

In [8]:
tb_carga_viral_consolidado['UltCV_2009'] = tb_carga_viral_consolidado['UltCV_2009'].fillna(0).astype(np.int64)
tb_carga_viral_consolidado['UltCV_2010'] = tb_carga_viral_consolidado['UltCV_2010'].fillna(0).astype(np.int64)
tb_carga_viral_consolidado['UltCV_2011'] = tb_carga_viral_consolidado['UltCV_2011'].fillna(0).astype(np.int64)
tb_carga_viral_consolidado['UltCV_2012'] = tb_carga_viral_consolidado['UltCV_2012'].fillna(0).astype(np.int64)
tb_carga_viral_consolidado['UltCV_2013'] = tb_carga_viral_consolidado['UltCV_2013'].fillna(0).astype(np.int64)
tb_carga_viral_consolidado['UltCV_2014'] = tb_carga_viral_consolidado['UltCV_2014'].fillna(0).astype(np.int64)
tb_carga_viral_consolidado['UltCV_2015'] = tb_carga_viral_consolidado['UltCV_2015'].fillna(0).astype(np.int64)
tb_carga_viral_consolidado['UltCV_2016'] = tb_carga_viral_consolidado['UltCV_2016'].fillna(0).astype(np.int64)
tb_carga_viral_consolidado['UltCV_2017'] = tb_carga_viral_consolidado['UltCV_2017'].fillna(0).astype(np.int64)
tb_carga_viral_consolidado['UltCV_2018'] = tb_carga_viral_consolidado['UltCV_2018'].fillna(0).astype(np.int64)
tb_carga_viral_consolidado['UltCV_2019'] = tb_carga_viral_consolidado['UltCV_2019'].fillna(0).astype(np.int64)
tb_carga_viral_consolidado['UltCV_2020'] = tb_carga_viral_consolidado['UltCV_2020'].fillna(0).astype(np.int64)
tb_carga_viral_consolidado['UltCV_2021'] = tb_carga_viral_consolidado['UltCV_2021'].fillna(0).astype(np.int64)

## Salvar como arquivo hdf5 (formato bin√°rio)

In [9]:
tb_carga_viral_consolidado

,cod_pac,cod_pac_final,cod_ibge_udm,paciente_gestante,motivo_exame,cd_ibge_coletora,cd_ibge_executora,data_solicitacao,data_hora_coleta,data_do_resultado,condicoes_chegada,contagem_cd4,perc_cd4,contagem_cd8,perc_cd8,sintomatico,dt_primeira_dispensa,dt_ultimo_exame,HIV,PriCV,UltCV_2009,UltCV_2010,UltCV_2011,UltCV_2012,UltCV_2013,UltCV_2014,UltCV_2015,UltCV_2016,UltCV_2017,UltCV_2018,UltCV_2019,UltCV_2020,UltCV_2021,UltCD4_antesTARV,tipo_unidade
0,99971268,58500928,4314407.0,2.0,2.0,4314407.0,4315602,2002-05-14 00:00:00.000,2002-05-15 07:30:00.000,2002-06-11 10:01:43.153,1,394.0,NaN,434.0,NaN,A,NaN,2003-02-26 09:00:00.000,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,SAE
1,99969034,99969034,4314407.0,2.0,1.0,4314407.0,4315602,2010-06-14 00:00:00.000,2010-06-16 09:15:00.000,2010-06-24 16:21:40.340,1,380.0,13.81,1975.0,71.75,A,2014-04-14 16:00:56.000,2015-11-23 08:00:00.000,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,SAE
2,99971268,58500928,4314407.0,2.0,1.0,4314407.0,4315602,2003-02-25 00:00:00.000,2003-02-26 09:00:00.000,2003-03-17 16:44:36.983,1,88.0,NaN,310.0,NaN,S,NaN,2003-02-26 09:00:00.000,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,SAE
3,99968955,99968955,4314407.0,2.0,2.0,4314407.0,4315602,2003-02-14 00:00:00.000,2003-03-12 08:50:00.000,2003-04-02 16:39:51.530,1,696.0,NaN,1943.0,NaN,A,2008-05-26 00:00:00.000,2016-11-09 08:00:00.000,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,SAE
4,7877,7877,4202909.0,2.0,2.0,4202909.0,4205407,2002-01-30 00:00:00.000,2002-01-30 08:00:00.000,2002-02-08 08:40:30.427,1,851.0,44.58,597.0,31.27,A,2006-10-25 00:00:00.000,2011-04-04 14:00:00.000,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,SAE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9093644,239455,239455,3550308.0,3.0,2.0,3550308.0,3550308,2021-07-07 00:00:00.000,2021-07-07 08:00:00.000,2021-07-12 09:19:47.000,1,209.0,13.97,916.0,61.30,A,2020-06-09 10:49:15.000,2021-07-07 08:00:00.000,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,AME
9093645,99052380,99052380,4205407.0,NaN,2.0,4205407.0,4205407,2021-07-28 00:00:00.000,2021-07-28 09:00:00.000,2021-08-05 13:54:16.000,1,643.0,28.76,911.0,40.72,A,2018-03-12 08:23:18.000,2021-07-28 09:00:00.000,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,NaN
9093646,337021,337021,3550308.0,NaN,2.0,3550308.0,3550308,2021-08-05 00:00:00.000,2021-08-05 07:00:00.000,2021-08-05 16:33:54.000,1,1112.0,32.91,1078.0,31.91,A,2021-08-09 19:57:44.000,2021-08-05 07:00:00.000,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,HOSP
9093647,99804142,99804142,4110078.0,NaN,2.0,4110078.0,4113700,NaN,2019-03-14 07:00:00.000,2019-03-15 11:00:06.000,1,115.0,19.38,357.0,60.04,S,2007-05-19 00:00:00.000,2019-03-14 07:00:00.000,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,NaN
9093648,162949,162949,4110078.0,1.0,NaN,4110078.0,4113700,NaN,2019-08-12 07:00:00.000,2019-08-14 12:02:12.000,1,566.0,24.24,1455.0,62.34,NaN,2019-07-04 10:30:17.000,2019-08-12 07:00:00.000,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,NaN

In [10]:
vaex_tb_carga_viral_consolidado = vaex.from_pandas(tb_carga_viral_consolidado, copy_index=True)

In [11]:
vaex_tb_carga_viral_consolidado.export('tb_carga_viral_consolidado.hdf5')