# Script Python - Jupyter - Banco de Dispensa  
# 01/09/21 por Mikael Lemos - V1.0

## Carregando as bibliotecas

In [1]:
import os
import openpyxl
import black 
import numpy as np
import pandas as pd
import pypolars as pl
import pyreadstat
from datetime import datetime, date, time, timezone
import pyflowchart
import vaex
from pathlib import Path
import h5py

WARNING!
py-polars was renamed to polars, please install polars!
https://pypi.org/project/polars/

## Carregar arquivo hdf5

In [2]:
tb_dispensas_esquemas_udm = vaex.open('tb_dispensas_esquemas_udm.hdf5')

## Verificar categoria de dispensa - Colocar apenas dispensas O ou G

In [3]:
tb_dispensas_esquemas_udm['categoria_disp'].value_counts()

O    16508595
G       90457
dtype: int64

## Caso não existam apenas dispensas do tipo O ou G - filtro para dispensas do tipo O ou G

In [4]:
tb_dispensas_esquemas_udm['categoria_disp'] = tb_dispensas_esquemas_udm['categoria_disp'].astype(str)
tb_dispensas_esquemas_udm = tb_dispensas_esquemas_udm[tb_dispensas_esquemas_udm['categoria_disp'].str.contains("O|G")]

## Passo 1: Criando as variáveis de data

## Manipulando formatos de data

In [5]:
tb_dispensas_esquemas_udm['data_dispensa'] = tb_dispensas_esquemas_udm['data_dispensa'].astype('datetime64')
tb_dispensas_esquemas_udm['data_dispensa_anterior'] = tb_dispensas_esquemas_udm['data_dispensa_anterior'].astype('datetime64')
tb_dispensas_esquemas_udm['data_dispensa_posterior'] = tb_dispensas_esquemas_udm['data_dispensa_posterior'].astype('datetime64')
tb_dispensas_esquemas_udm['data_PriDisp'] = tb_dispensas_esquemas_udm['data_PriDisp'].astype('datetime64')
tb_dispensas_esquemas_udm['data_ultima_dispensa'] = tb_dispensas_esquemas_udm['data_ultima_dispensa'].astype('datetime64')

In [6]:
tb_dispensas_esquemas_udm['data_dispensa'] = tb_dispensas_esquemas_udm['data_dispensa'].astype('datetime64')
tb_dispensas_esquemas_udm['data_dispensa_anterior'] = tb_dispensas_esquemas_udm['data_dispensa_anterior'].astype('datetime64')
tb_dispensas_esquemas_udm['data_dispensa_posterior'] = tb_dispensas_esquemas_udm['data_dispensa_posterior'].astype('datetime64')
tb_dispensas_esquemas_udm['data_PriDisp'] = tb_dispensas_esquemas_udm['data_PriDisp'].astype('datetime64')
tb_dispensas_esquemas_udm['data_ultima_dispensa'] = tb_dispensas_esquemas_udm['data_ultima_dispensa'].astype('datetime64')

## Criação das variáveis: dt_disp, anodisp,dt_disp_anterior, anodisp_anterior, dtdisp_mes, dt_Pridisp

In [7]:
tb_dispensas_esquemas_udm['dt_disp'] = tb_dispensas_esquemas_udm['data_dispensa'].dt.strftime('%Y-%m-%d')
tb_dispensas_esquemas_udm['anodisp'] = tb_dispensas_esquemas_udm['data_dispensa'].dt.strftime('%Y')
tb_dispensas_esquemas_udm['dt_disp_anterior'] = tb_dispensas_esquemas_udm['data_dispensa_anterior'].dt.strftime('%Y-%m-%d')
tb_dispensas_esquemas_udm['anodisp_anterior'] = tb_dispensas_esquemas_udm['data_dispensa_anterior'].dt.strftime('%Y')
tb_dispensas_esquemas_udm['dt_disp_posterior'] = tb_dispensas_esquemas_udm['data_dispensa_posterior'].dt.strftime('%Y-%m-%d')
tb_dispensas_esquemas_udm['anodisp_posterior'] = tb_dispensas_esquemas_udm['data_dispensa_posterior'].dt.strftime('%Y')
tb_dispensas_esquemas_udm['dt_Ultdisp'] = tb_dispensas_esquemas_udm['data_ultima_dispensa'].dt.strftime('%Y-%m-%d')
tb_dispensas_esquemas_udm['AnoUltDisp'] = tb_dispensas_esquemas_udm['data_ultima_dispensa'].dt.strftime('%Y')
tb_dispensas_esquemas_udm['dt_Pridisp'] = tb_dispensas_esquemas_udm['data_PriDisp'].dt.strftime('%Y-%m-%d')
tb_dispensas_esquemas_udm['AnoPriDisp'] = tb_dispensas_esquemas_udm['data_PriDisp'].dt.strftime('%Y')
tb_dispensas_esquemas_udm['dtdisp_mes'] = tb_dispensas_esquemas_udm['data_dispensa'].dt.strftime('%m-%Y')

In [8]:
tb_dispensas_esquemas_udm['dt_disp'] = tb_dispensas_esquemas_udm['data_dispensa'].dt.strftime('%Y-%m-%d')
tb_dispensas_esquemas_udm['anodisp'] = tb_dispensas_esquemas_udm['data_dispensa'].dt.strftime('%Y')
tb_dispensas_esquemas_udm['dt_disp_anterior'] = tb_dispensas_esquemas_udm['data_dispensa_anterior'].dt.strftime('%Y-%m-%d')
tb_dispensas_esquemas_udm['anodisp_anterior'] = tb_dispensas_esquemas_udm['data_dispensa_anterior'].dt.strftime('%Y')
tb_dispensas_esquemas_udm['dt_disp_posterior'] = tb_dispensas_esquemas_udm['data_dispensa_posterior'].dt.strftime('%Y-%m-%d')
tb_dispensas_esquemas_udm['anodisp_posterior'] = tb_dispensas_esquemas_udm['data_dispensa_posterior'].dt.strftime('%Y')
tb_dispensas_esquemas_udm['dt_Ultdisp'] = tb_dispensas_esquemas_udm['data_ultima_dispensa'].dt.strftime('%Y-%m-%d')
tb_dispensas_esquemas_udm['AnoUltDisp'] = tb_dispensas_esquemas_udm['data_ultima_dispensa'].dt.strftime('%Y')
tb_dispensas_esquemas_udm['dt_Pridisp'] = tb_dispensas_esquemas_udm['data_PriDisp'].dt.strftime('%Y-%m-%d')
tb_dispensas_esquemas_udm['AnoPriDisp'] = tb_dispensas_esquemas_udm['data_PriDisp'].dt.strftime('%Y')
tb_dispensas_esquemas_udm['dtdisp_mes'] = tb_dispensas_esquemas_udm['data_dispensa'].dt.strftime('%m-%Y')

## Criar variáveis : dt_disp_min e dt_disp_max

In [9]:
tb_dispensas_esquemas_udm['dt_disp_min'] = tb_dispensas_esquemas_udm['dt_Pridisp']
tb_dispensas_esquemas_udm['dt_disp_max'] = tb_dispensas_esquemas_udm['dt_Ultdisp']

## Verificar variáveis

In [10]:
tb_dispensas_esquemas_udm.info()

## Unificar colunas para criar variável da última dispensa de cada ano - UltDispAno

In [11]:
def combine(a,b,c,d,e,f,g,h,i,j,k,l,m):
    return a +  b + c +  d +  e +  f +  g +  h +  i +  j +  k +  l +  m

In [12]:
tb_dispensas_esquemas_udm['UltDispAno'] = combine(tb_dispensas_esquemas_udm.UltDisp_2009,tb_dispensas_esquemas_udm.UltDisp_2010,tb_dispensas_esquemas_udm.UltDisp_2011,tb_dispensas_esquemas_udm.UltDisp_2012,tb_dispensas_esquemas_udm.UltDisp_2013, tb_dispensas_esquemas_udm.UltDisp_2014,tb_dispensas_esquemas_udm.UltDisp_2015,tb_dispensas_esquemas_udm.UltDisp_2016,tb_dispensas_esquemas_udm.UltDisp_2017,tb_dispensas_esquemas_udm.UltDisp_2018,tb_dispensas_esquemas_udm.UltDisp_2019,tb_dispensas_esquemas_udm.UltDisp_2020,tb_dispensas_esquemas_udm.UltDisp_2021)

## Checar última dispensa ano - UltDispAno

In [13]:
tb_dispensas_esquemas_udm['UltDispAno'].value_counts()

0    13793842
1     2805210
dtype: int64

## Remover variáveis/colunas não utilizadas

In [14]:
colunas_drop = [tb_dispensas_esquemas_udm.data_dispensa, tb_dispensas_esquemas_udm.data_dispensa_anterior, tb_dispensas_esquemas_udm.data_dispensa_posterior,tb_dispensas_esquemas_udm.data_PriDisp,tb_dispensas_esquemas_udm.data_ultima_dispensa, tb_dispensas_esquemas_udm.UltDisp_2009, tb_dispensas_esquemas_udm.UltDisp_2010, tb_dispensas_esquemas_udm.UltDisp_2011, tb_dispensas_esquemas_udm.UltDisp_2012, tb_dispensas_esquemas_udm.UltDisp_2013, tb_dispensas_esquemas_udm.UltDisp_2014, tb_dispensas_esquemas_udm.UltDisp_2015, tb_dispensas_esquemas_udm.UltDisp_2016, tb_dispensas_esquemas_udm.UltDisp_2017, tb_dispensas_esquemas_udm.UltDisp_2018, tb_dispensas_esquemas_udm.UltDisp_2019, tb_dispensas_esquemas_udm.UltDisp_2020, tb_dispensas_esquemas_udm.UltDisp_2021]

In [15]:
tb_dispensas_esquemas_udm  = tb_dispensas_esquemas_udm.drop(colunas_drop, inplace=False,  check=True )

## Variável PriDisp_arpp

In [16]:
tb_dispensas_esquemas_udm['PriDisp_arpp'] = tb_dispensas_esquemas_udm['PriDisp']

In [17]:
tb_dispensas_esquemas_udm['PriDisp_arpp'] = tb_dispensas_esquemas_udm.PriDisp_arpp.astype('str')

In [18]:
datas_ig = tb_dispensas_esquemas_udm.dt_disp == tb_dispensas_esquemas_udm.dt_disp_min

In [19]:
if datas_ig is True:
   tb_dispensas_esquemas_udm['PriDisp_arpp'] = tb_dispensas_esquemas_udm.PriDisp_arpp.str.title().str.replace('0', '1')
else:
   tb_dispensas_esquemas_udm['PriDisp_arpp'] = tb_dispensas_esquemas_udm.PriDisp_arpp.str.title().str.replace('0', '0')

In [20]:
tb_dispensas_esquemas_udm['PriDisp_arpp'].value_counts()

0    16367949
1      231103
dtype: int64

# Crosstabs - arquivo: 1 Informações Gerais - sheet: Gerais Agosto 2021

## Crosstabs variáveis: anodisp * UltDispAno

In [21]:
dispensa_crosstab =  tb_dispensas_esquemas_udm['anodisp','UltDispAno']

In [22]:
dispensa_crosstab

#           anodisp    UltDispAno
0           2018       0
1           2018       0
2           2018       0
3           2018       0
4           2018       0
...         ...        ...
16,599,047  2019       0
16,599,048  2019       0
16,599,049  2018       0
16,599,050  2019       1
16,599,051  2018       0

In [23]:
dispensa_crosstab = dispensa_crosstab.to_pandas_df(['anodisp','UltDispAno'])

In [24]:
dispensa_crosstab = dispensa_crosstab.groupby(['anodisp','UltDispAno']).size().reset_index(name='Total')

In [25]:
table_crosstab = pd.pivot_table(dispensa_crosstab, values='Total', index=['anodisp'],
                    columns=[ 'UltDispAno'], aggfunc=np.sum)

In [26]:
table_crosstab

UltDispAno        0       1
anodisp
2018        4336663  645588
2019        4152437  695595
2020        3415358  728248
2021        1889384  735779

## Soma das colunas

In [27]:
table_crosstab['Total'] = table_crosstab.loc[:, 0:].apply(np.sum, axis=1)

## Soma de linhas de cada coluna

In [28]:
total = table_crosstab.sum()
total.name = 'Total'
table_crosstab = table_crosstab.append(total.transpose())

## Crosstabs variáveis: anodisp * PriDisp

In [29]:
dispensa_crosstab2 =  tb_dispensas_esquemas_udm['anodisp','PriDisp']

In [30]:
dispensa_crosstab2

#           anodisp    PriDisp
0           2018       0
1           2018       0
2           2018       0
3           2018       0
4           2018       0
...         ...        ...
16,599,047  2019       0
16,599,048  2019       0
16,599,049  2018       0
16,599,050  2019       0
16,599,051  2018       0

In [31]:
dispensa_crosstab2 = dispensa_crosstab2.to_pandas_df(['anodisp','PriDisp'])

In [32]:
dispensa_crosstab2 = dispensa_crosstab2.groupby(['anodisp','PriDisp']).size().reset_index(name='Total')

In [33]:
table_crosstab2 = pd.pivot_table(dispensa_crosstab2, values='Total', index=['anodisp'],
                    columns=[ 'PriDisp'], aggfunc=np.sum)

In [34]:
table_crosstab2

PriDisp        0      1
anodisp
2018     4913662  68589
2019     4779700  68332
2020     4088535  55071
2021     2586052  39111

## Soma das colunas

In [35]:
table_crosstab2['Total'] = table_crosstab2.loc[:, 0:].apply(np.sum, axis=1)

## Soma das linhas de cada coluna

In [36]:
total = table_crosstab2.sum()
total.name = 'Total'
table_crosstab2 = table_crosstab2.append(total.transpose())

## Tabela de frequência / Porcentagem de duplicados/não duplicados com base na ultima dispensa da vida (UltDispVida)

In [37]:
dispensa_crosstab3 =  tb_dispensas_esquemas_udm['codigo_paciente','UltDispVida']

In [38]:
dispensa_crosstab3 = dispensa_crosstab3.to_pandas_df(['codigo_paciente','UltDispVida'])

In [39]:
dispensa_crosstab3 = pd.DataFrame(dispensa_crosstab3.value_counts())

In [40]:
dispensa_crosstab3

                               0
codigo_paciente UltDispVida
87600010        0            112
14100054        0             87
99802270        0             73
19661           0             72
99353632        0             68
...                          ...
90500029        1              1
264973          1              1
90500030        1              1
90500031        1              1
99999999        1              1

[1655005 rows x 1 columns]

## Separar primary case '0' = 1

In [41]:
dispensa_crosstab3 = dispensa_crosstab3.rename(columns={0: 'Frequency'})

In [42]:
dispensa_crosstab3_primary =  dispensa_crosstab3.query('Frequency == 1')

In [43]:
total = dispensa_crosstab3_primary.sum()
total.name = 'Primary Case'
dispensa_crosstab3_primary = dispensa_crosstab3_primary.append(total.transpose())

In [44]:
dispensa_crosstab3_primary = dispensa_crosstab3_primary.iloc[[-1]]

In [45]:
dispensa_crosstab3_primary

              Frequency
Primary Case     856490

## Separar duplicate case '0' > 1

In [46]:
dispensa_crosstab3_duplicate =  dispensa_crosstab3.query('Frequency > 1')

In [47]:
total = dispensa_crosstab3_duplicate.sum()
total.name = 'Duplicate Case'
dispensa_crosstab3_duplicate = dispensa_crosstab3_duplicate.append(total.transpose())

In [48]:
dispensa_crosstab3_duplicate = dispensa_crosstab3_duplicate.iloc[[-1]]

In [49]:
dispensa_crosstab3_duplicate

                Frequency
Duplicate Case   15742562

## Unir tabelas para criar 'Indicator of each last matching case as Primary' - UltDispVida

In [50]:
table_crosstab3 = pd.concat([dispensa_crosstab3_primary, dispensa_crosstab3_duplicate])

In [51]:
table_crosstab3

                Frequency
Primary Case       856490
Duplicate Case   15742562

## Coluna de Porcentagem

In [52]:
table_crosstab3['Percent'] = (table_crosstab3['Frequency'] / table_crosstab3['Frequency'].sum()) * 100

In [53]:
table_crosstab3['Percent'] = pd.Series([round(val, 1) for val in table_crosstab3['Percent']], index = table_crosstab3.index)

## Calculando total

In [54]:
total = table_crosstab3.sum()
total.name = 'Total'
table_crosstab3 = table_crosstab3.append(total.transpose())

## Converter colunas de float64 para int32

In [55]:
table_crosstab3['Frequency'] = np.nan_to_num(table_crosstab3['Frequency']).astype(int)

# Crosstabs - arquivo: 1 Informações Gerais - sheet: Gerais - Crosstabs CD4 - tabela: tb_cd4_consolidado.txt

## Carregar arquivo hdf5

In [56]:
tb_cd4_consolidado = vaex.open('tb_cd4_consolidado.hdf5')

In [57]:
tb_cd4_consolidado.info()

## Passo 1 : Criando Variável de data

In [58]:
tb_cd4_consolidado[ "('data_hora_coleta',)"] = tb_cd4_consolidado[ "('data_hora_coleta',)"].astype('datetime64')

In [59]:
tb_cd4_consolidado[ "('data_hora_coleta',)"] = tb_cd4_consolidado[ "('data_hora_coleta',)"].astype('datetime64')

In [60]:
tb_cd4_consolidado['anocoleta'] = tb_cd4_consolidado["('data_hora_coleta',)"].dt.strftime('%Y')

In [61]:
tb_cd4_consolidado['anocoleta'] = tb_cd4_consolidado["('data_hora_coleta',)"].dt.strftime('%Y')

## Unificar colunas para criar variável da última dispensa de cada ano - UltCD4Ano

In [62]:
def combine(a,b,c,d,e,f,g,h,i,j,k,l,m):
    return a +  b + c +  d +  e +  f +  g +  h +  i +  j +  k +  l +  m

In [63]:
tb_cd4_consolidado['UltCD4Ano'] = combine(tb_cd4_consolidado["('UltCD4_2009',)"] ,tb_cd4_consolidado["('UltCD4_2010',)"],tb_cd4_consolidado["('UltCD4_2011',)"],tb_cd4_consolidado["('UltCD4_2012',)"],tb_cd4_consolidado["('UltCD4_2013',)"], tb_cd4_consolidado["('UltCD4_2014',)"],tb_cd4_consolidado["('UltCD4_2015',)"],tb_cd4_consolidado["('UltCD4_2016',)"],tb_cd4_consolidado["('UltCD4_2017',)"],tb_cd4_consolidado["('UltCD4_2018',)"],tb_cd4_consolidado["('UltCD4_2019',)"],tb_cd4_consolidado["('UltCD4_2020',)"],tb_cd4_consolidado["('UltCD4_2021',)"])

## Crosstabs variáveis: anocoleta * UltCD4Ano

In [64]:
cd4_crosstab =  tb_cd4_consolidado['anocoleta','UltCD4Ano']

In [65]:
cd4_crosstab

#          anocoleta    UltCD4Ano
0          2002         0
1          2010         1
2          2003         0
3          2003         0
4          2002         0
...        ...          ...
9,093,644  2021         1
9,093,645  2021         1
9,093,646  2021         1
9,093,647  2019         1
9,093,648  2019         1

In [66]:
cd4_crosstab = cd4_crosstab.to_pandas_df(['anocoleta','UltCD4Ano'])

In [67]:
cd4_crosstab = cd4_crosstab.groupby(['anocoleta','UltCD4Ano']).size().reset_index(name='Total')

In [68]:
cd4_crosstab = pd.pivot_table(cd4_crosstab, values='Total', index=['anocoleta'],
                    columns=[ 'UltCD4Ano'], aggfunc=np.sum)

In [69]:
cd4_crosstab.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22 entries, 2000 to 2021
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       22 non-null     float64
 1   1       13 non-null     float64
dtypes: float64(2)
memory usage: 528.0+ bytes

In [70]:
cd4_crosstab['Total'] = cd4_crosstab.loc[:, 0:].apply(np.sum, axis=1)

In [71]:
total = cd4_crosstab.sum()
total.name = 'Total'
cd4_crosstab = cd4_crosstab.append(total.transpose())

## Converter colunas de float64 para int32

In [72]:
cd4_crosstab[[1]] = np.nan_to_num(cd4_crosstab[[1]]).astype(int)
cd4_crosstab[[0]] = np.nan_to_num(cd4_crosstab[[0]]).astype(int)
cd4_crosstab['Total'] = np.nan_to_num(cd4_crosstab['Total']).astype(int)

In [73]:
cd4_crosstab

UltCD4Ano        0        1    Total
anocoleta
2000           125        0      125
2001         10179        0    10179
2002        125139        0   125139
2003        173516        0   173516
2004        241902        0   241902
2005        330895        0   330895
2006        391422        0   391422
2007        443314        0   443314
2008        488068        0   488068
2009        253415   272588   526003
2010        259889   289771   549660
2011        278084   312823   590907
2012        288245   332012   620257
2013        307011   357169   664180
2014        312905   383477   696382
2015        309794   413154   722948
2016        172957   379789   552746
2017        134726   330434   465160
2018        141071   352879   493950
2019        113722   341801   455523
2020         64156   241877   306033
2021         29974   215366   245340
Total      4870509  4223140  9093649

## Crosstabs variáveis: anocoleta * PriCD4

In [74]:
cd4_crosstab2 =  tb_cd4_consolidado['anocoleta',"('PriCD4',)" ]

In [75]:
cd4_crosstab2

#          anocoleta    ('PriCD4',)
0          2002         1
1          2010         0
2          2003         0
3          2003         0
4          2002         1
...        ...          ...
9,093,644  2021         0
9,093,645  2021         0
9,093,646  2021         0
9,093,647  2019         0
9,093,648  2019         1

In [76]:
cd4_crosstab2 = cd4_crosstab2.to_pandas_df(['anocoleta',"('PriCD4',)"])

In [77]:
cd4_crosstab2 = cd4_crosstab2.groupby(['anocoleta',"('PriCD4',)"]).size().reset_index(name='Total')

In [78]:
cd4_crosstab2 = pd.pivot_table(cd4_crosstab2, values='Total', index=['anocoleta'],
                    columns=["('PriCD4',)"], aggfunc=np.sum)

In [79]:
cd4_crosstab2['Total'] = cd4_crosstab2.loc[:, 0:].apply(np.sum, axis=1)

In [80]:
total = cd4_crosstab2.sum()
total.name = 'Total'
cd4_crosstab2 = cd4_crosstab2.append(total.transpose())

In [81]:
tb_cd4_consolidado.info()

## Criando variáveis: dt_disp_min, diasColetaDispensa2, dt_coleta - a partir de variáveis de data - transformar variáveis em para datetime

In [82]:
cd4_crosstab3 = tb_cd4_consolidado.to_pandas_df(["('data_hora_coleta',)","('dt_primeira_dispensa',)", "('PriCD4',)" ])

In [83]:
cd4_crosstab3[ "('dt_primeira_dispensa',)"] = cd4_crosstab3[ "('dt_primeira_dispensa',)"].astype('datetime64')

In [84]:
cd4_crosstab3[ "('dt_primeira_dispensa',)"] = cd4_crosstab3[ "('dt_primeira_dispensa',)"].astype('datetime64')

In [85]:
cd4_crosstab3

        ('data_hora_coleta',) ('dt_primeira_dispensa',)  ('PriCD4',)
0         2002-05-15 07:30:00                       NaT            1
1         2010-06-16 09:15:00       2014-04-14 16:00:56            0
2         2003-02-26 09:00:00                       NaT            0
3         2003-03-12 08:50:00       2008-05-26 00:00:00            0
4         2002-01-30 08:00:00       2006-10-25 00:00:00            1
...                       ...                       ...          ...
9093644   2021-07-07 08:00:00       2020-06-09 10:49:15            0
9093645   2021-07-28 09:00:00       2018-03-12 08:23:18            0
9093646   2021-08-05 07:00:00       2021-08-09 19:57:44            0
9093647   2019-03-14 07:00:00       2007-05-19 00:00:00            0
9093648   2019-08-12 07:00:00       2019-07-04 10:30:17            1

[9093649 rows x 3 columns]

## Criação das variáveis

In [86]:
cd4_crosstab3['dt_coleta'] = cd4_crosstab3["('data_hora_coleta',)"].dt.strftime('%Y-%m-%d')
cd4_crosstab3['dt_disp_min'] = cd4_crosstab3["('dt_primeira_dispensa',)"].dt.strftime('%Y-%m-%d')

In [87]:
cd4_crosstab3['dt_coleta'] = pd.to_datetime(cd4_crosstab3['dt_coleta'])
cd4_crosstab3['dt_disp_min'] = pd.to_datetime(cd4_crosstab3['dt_disp_min'])

In [88]:
cd4_crosstab3['diasColetaDispensa2'] = (cd4_crosstab3['dt_coleta'] - cd4_crosstab3['dt_disp_min']).dt.days

In [89]:
cd4_crosstab3['diasColetaDispensa2'] = cd4_crosstab3['diasColetaDispensa2'].fillna(999999999)

In [90]:
cd4_crosstab3['diasColetaDispensa2'].value_counts()

 999999999.0    611185
 0.0             33841
-28.0            12016
 1.0             11948
-35.0            11559
                 ...
 17400.0             1
-6633.0              1
-6932.0              1
 17411.0             1
 8073.0              1
Name: diasColetaDispensa2, Length: 14825, dtype: int64

In [91]:
cd4_crosstab3

,"('data_hora_coleta',)","('dt_primeira_dispensa',)","('PriCD4',)",dt_coleta,dt_disp_min,diasColetaDispensa2
0,2002-05-15 07:30:00,NaT,1,2002-05-15,NaT,999999999.0
1,2010-06-16 09:15:00,2014-04-14 16:00:56,0,2010-06-16,2014-04-14,-1398.0
2,2003-02-26 09:00:00,NaT,0,2003-02-26,NaT,999999999.0
3,2003-03-12 08:50:00,2008-05-26 00:00:00,0,2003-03-12,2008-05-26,-1902.0
4,2002-01-30 08:00:00,2006-10-25 00:00:00,1,2002-01-30,2006-10-25,-1729.0
...,...,...,...,...,...,...
9093644,2021-07-07 08:00:00,2020-06-09 10:49:15,0,2021-07-07,2020-06-09,393.0
9093645,2021-07-28 09:00:00,2018-03-12 08:23:18,0,2021-07-28,2018-03-12,1234.0
9093646,2021-08-05 07:00:00,2021-08-09 19:57:44,0,2021-08-05,2021-08-09,-4.0
9093647,2019-03-14 07:00:00,2007-05-19 00:00:00,0,2019-03-14,2007-05-19,4317.0
9093648,2019-08-12 07:00:00,2019-07-04 10:30:17,1,2019-08-12,2019-07-04,39.0

## Correções na coluna: diasColetaDispensa2 - int32

In [92]:
cd4_crosstab3['diasColetaDispensa2'] = np.nan_to_num(cd4_crosstab3['diasColetaDispensa2']).astype(int)

## módulo dos valores

In [93]:
#cd4_crosstab3['diasColetaDispensa2'] = cd4_crosstab3['diasColetaDispensa2'].abs()

## Criar variável : priCD4_antesTARV

In [94]:
cd4_crosstab3['priCD4_antesTARV'] = 0

## Substituir 0 na variável priCD4_antesTARV de acordo com as condições:

In [95]:
cd4_crosstab3 = cd4_crosstab3.rename(columns={"('PriCD4',)": "PriCD4"})

In [96]:
cd4_crosstab3.loc[(cd4_crosstab3['diasColetaDispensa2'] <= 15) & (cd4_crosstab3['PriCD4'] == 1), 'priCD4_antesTARV'] = 1  
cd4_crosstab3.loc[(cd4_crosstab3['diasColetaDispensa2'] == 999999999) & (cd4_crosstab3['PriCD4'] == 1), 'priCD4_antesTARV'] = 1

## Tabela anocoleta * priCD4_antesTARV

In [97]:
cd4_crosstab3['anocoleta'] = cd4_crosstab3["('data_hora_coleta',)"].dt.strftime('%Y')

In [98]:
cd4_crosstab3 = cd4_crosstab3.groupby(['anocoleta','priCD4_antesTARV']).size().reset_index(name='Total')

In [99]:
cd4_crosstab3

   anocoleta  priCD4_antesTARV   Total
0       2000                 0     101
1       2000                 1      24
2       2001                 0    3687
3       2001                 1    6492
4       2002                 0   68371
5       2002                 1   56768
6       2003                 0  137033
7       2003                 1   36483
8       2004                 0  196647
9       2004                 1   45255
10      2005                 0  280862
11      2005                 1   50033
12      2006                 0  352262
13      2006                 1   39160
14      2007                 0  403751
15      2007                 1   39563
16      2008                 0  450324
17      2008                 1   37744
18      2009                 0  488083
19      2009                 1   37920
20      2010                 0  511015
21      2010                 1   38645
22      2011                 0  549154
23      2011                 1   41753
24      2012                 0  578515
25      2012                 1   41742
26      2013                 0  618930
27      2013                 1   45250
28      2014                 0  648812
29      2014                 1   47570
30      2015                 0  672286
31      2015                 1   50662
32      2016                 0  502555
33      2016                 1   50191
34      2017                 0  414024
35      2017                 1   51136
36      2018                 0  440867
37      2018                 1   53083
38      2019                 0  403076
39      2019                 1   52447
40      2020                 0  264841
41      2020                 1   41192
42      2021                 0  215659
43      2021                 1   29681

In [100]:
cd4_crosstab3 = pd.pivot_table(cd4_crosstab3, values='Total', index=['anocoleta'],
                    columns=["priCD4_antesTARV"], aggfunc=np.sum)

In [101]:
cd4_crosstab3['Total'] = cd4_crosstab3.loc[:, 0:].apply(np.sum, axis=1)

In [102]:
total = cd4_crosstab3.sum()
total.name = 'Total'
cd4_crosstab3 = cd4_crosstab3.append(total.transpose())

## Identificação de casos duplicados - variáveis : cod_pac_final, CD4maispertoPriDisp, dt_coleta

In [103]:
cd4_crosstab4 = tb_cd4_consolidado.to_pandas_df(["('cod_pac_final',)","('data_hora_coleta',)","('dt_primeira_dispensa',)", "('PriCD4',)" ])

In [104]:
cd4_crosstab4[ "('dt_primeira_dispensa',)"] = cd4_crosstab4[ "('dt_primeira_dispensa',)"].astype('datetime64')

In [105]:
cd4_crosstab4[ "('dt_primeira_dispensa',)"] = cd4_crosstab4[ "('dt_primeira_dispensa',)"].astype('datetime64')

In [106]:
cd4_crosstab4['dt_coleta'] = cd4_crosstab4["('data_hora_coleta',)"].dt.strftime('%Y-%m-%d')
cd4_crosstab4['dt_disp_min'] = cd4_crosstab4["('dt_primeira_dispensa',)"].dt.strftime('%Y-%m-%d')

In [107]:
cd4_crosstab4['dt_coleta'] = pd.to_datetime(cd4_crosstab4['dt_coleta'])
cd4_crosstab4['dt_disp_min'] = pd.to_datetime(cd4_crosstab4['dt_disp_min'])

In [108]:
cd4_crosstab4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9093649 entries, 0 to 9093648
Data columns (total 6 columns):
 #   Column                     Dtype
---  ------                     -----
 0   ('cod_pac_final',)         int64
 1   ('data_hora_coleta',)      datetime64[ns]
 2   ('dt_primeira_dispensa',)  datetime64[ns]
 3   ('PriCD4',)                int64
 4   dt_coleta                  datetime64[ns]
 5   dt_disp_min                datetime64[ns]
dtypes: datetime64[ns](4), int64(2)
memory usage: 416.3 MB

In [109]:
cd4_crosstab4['diasColetaDispensa2'] = (cd4_crosstab4['dt_coleta'] - cd4_crosstab4['dt_disp_min']).dt.days

In [110]:
cd4_crosstab4['diasColetaDispensa2'] = cd4_crosstab4['diasColetaDispensa2'].fillna(999999999)

## diasColetaDispensa2 como int32

In [111]:
cd4_crosstab4['diasColetaDispensa2'] = np.nan_to_num(cd4_crosstab4['diasColetaDispensa2']).astype(int)

## Criar variável : CD4maispertoPriDisp_ano

In [112]:
cd4_crosstab4['CD4maispertoPriDisp_ano'] = 0

## Substituir 0 na variável CD4maispertoPriDisp_ano de acordo com as condições:

In [113]:
cd4_crosstab4 = cd4_crosstab4.rename(columns={"('PriCD4',)": "PriCD4"})

In [114]:
cd4_crosstab4 = cd4_crosstab4.rename(columns={"('cod_pac_final',)": "cod_pac_final"})

In [115]:
cd4_crosstab4.loc[(cd4_crosstab4['diasColetaDispensa2'] <= 15) & (cd4_crosstab4['diasColetaDispensa2'] >= -180), 'CD4maispertoPriDisp_ano'] = 1  
cd4_crosstab4.loc[(cd4_crosstab4['diasColetaDispensa2'] <= 15) & (cd4_crosstab4['diasColetaDispensa2'] >= -365), 'CD4maispertoPriDisp_ano'] = 1

## Criar tabela de casos duplicados cod_pac_final*CD4maispertoPriDisp_ano

In [116]:
cd4_crosstab5 =  cd4_crosstab4.drop(columns=["('data_hora_coleta',)", "('dt_primeira_dispensa',)", 'PriCD4','dt_disp_min', 'dt_coleta', 'diasColetaDispensa2' ])

In [117]:
cd4_crosstab5

         cod_pac_final  CD4maispertoPriDisp_ano
0             58500928                        0
1             99969034                        0
2             58500928                        0
3             99968955                        0
4                 7877                        0
...                ...                      ...
9093644         239455                        0
9093645       99052380                        0
9093646         337021                        1
9093647       99804142                        0
9093648         162949                        0

[9093649 rows x 2 columns]

In [118]:
cd4_crosstab5 = pd.DataFrame(cd4_crosstab5.value_counts())

## Separar primary case "0"/Frequency = 1

In [119]:
cd4_crosstab5 = cd4_crosstab5.rename(columns={0: 'Frequency'})

In [120]:
cd4_crosstab5_primary =  cd4_crosstab5.query('Frequency == 1')

In [121]:
total = cd4_crosstab5_primary.sum()
total.name = 'Primary Case'
cd4_crosstab5_primary = cd4_crosstab5_primary.append(total.transpose())

In [122]:
cd4_crosstab5_primary = cd4_crosstab5_primary.iloc[[-1]]

In [123]:
cd4_crosstab5_primary

              Frequency
Primary Case     680937

## Separar duplicate case "0"/Frequency > 1

In [124]:
cd4_crosstab5_duplicate =  cd4_crosstab5.query('Frequency > 1')

In [125]:
total = cd4_crosstab5_duplicate.sum()
total.name = 'Duplicate Case'
cd4_crosstab5_duplicate = cd4_crosstab5_duplicate.append(total.transpose())

In [126]:
cd4_crosstab5_duplicate = cd4_crosstab5_duplicate.iloc[[-1]]

In [127]:
cd4_crosstab5_duplicate

                Frequency
Duplicate Case    8412712

## Unir tabelas e criar o indicador primary/duplicate cases -  cod_pac_final*CD4maispertoPriDisp_ano

In [128]:
cd4_crosstab5 = pd.concat([cd4_crosstab5_primary, cd4_crosstab5_duplicate])

In [129]:
cd4_crosstab5

                Frequency
Primary Case       680937
Duplicate Case    8412712

In [130]:
cd4_crosstab5['Percent'] = (cd4_crosstab5['Frequency'] / cd4_crosstab5['Frequency'].sum()) * 100

In [131]:
cd4_crosstab5['Percent'] = pd.Series([round(val, 1) for val in cd4_crosstab5['Percent']], index = cd4_crosstab5.index)

In [132]:
total = cd4_crosstab5.sum()
total.name = 'Total'
cd4_crosstab5 = cd4_crosstab5.append(total.transpose())

## Converter coluna Frequency de float para int32

In [133]:
cd4_crosstab5['Frequency'] = np.nan_to_num(cd4_crosstab5['Frequency']).astype(int)

# Crosstabs - arquivo: 1 Informações Gerais - sheet: Gerais Agosto 2021 - Crosstabs CV - tabela: tb_carga_viral_consolidado.txt

In [134]:
tb_carga_viral_consolidado = vaex.open('tb_carga_viral_consolidado.hdf5')

In [135]:
tb_carga_viral_consolidado.info()

## Passo 1: Criando variável de data

In [136]:
tb_carga_viral_consolidado[ "('data_hora_coleta',)"] = tb_carga_viral_consolidado[ "('data_hora_coleta',)"].astype('datetime64')

In [137]:
tb_carga_viral_consolidado[ "('data_hora_coleta',)"] = tb_carga_viral_consolidado[ "('data_hora_coleta',)"].astype('datetime64')

In [138]:
tb_carga_viral_consolidado['anocoleta'] = tb_carga_viral_consolidado["('data_hora_coleta',)"].dt.strftime('%Y')

In [139]:
tb_carga_viral_consolidado['anocoleta'] = tb_carga_viral_consolidado["('data_hora_coleta',)"].dt.strftime('%Y')

## Criação da variável : UltCVAno

In [140]:
def combine(a,b,c,d,e,f,g,h,i,j,k,l,m):
    return a +  b + c +  d +  e +  f +  g +  h +  i +  j +  k +  l +  m

In [141]:
tb_carga_viral_consolidado['UltCVAno'] = combine(tb_carga_viral_consolidado["('UltCV_2009',)"] ,tb_carga_viral_consolidado["('UltCV_2010',)"],tb_carga_viral_consolidado["('UltCV_2011',)"],tb_carga_viral_consolidado["('UltCV_2012',)"],tb_carga_viral_consolidado["('UltCV_2013',)"], tb_carga_viral_consolidado["('UltCV_2014',)"],tb_carga_viral_consolidado["('UltCV_2015',)"],tb_carga_viral_consolidado["('UltCV_2016',)"],tb_carga_viral_consolidado["('UltCV_2017',)"],tb_carga_viral_consolidado["('UltCV_2018',)"],tb_carga_viral_consolidado["('UltCV_2019',)"],tb_carga_viral_consolidado["('UltCV_2020',)"],tb_carga_viral_consolidado["('UltCV_2021',)"])

## Crosstabs CV: anocoleta*UltCVAno

In [142]:
cv_crosstab =  tb_carga_viral_consolidado['anocoleta','UltCVAno']

In [143]:
cv_crosstab = cv_crosstab.to_pandas_df(['anocoleta','UltCVAno'])

In [144]:
cv_crosstab = cv_crosstab.groupby(['anocoleta','UltCVAno']).size().reset_index(name='Total')

In [145]:
cv_crosstab = pd.pivot_table(cv_crosstab, values='Total', index=['anocoleta'],
                    columns=[ 'UltCVAno'], aggfunc=np.sum)

In [146]:
cv_crosstab

UltCVAno          0         1
anocoleta
2000          125.0       NaN
2001        10179.0       NaN
2002       125139.0       NaN
2003       173516.0       NaN
2004       241902.0       NaN
2005       330895.0       NaN
2006       391422.0       NaN
2007       443314.0       NaN
2008       488068.0       NaN
2009       253415.0  272588.0
2010       259889.0  289771.0
2011       278084.0  312823.0
2012       288245.0  332012.0
2013       307011.0  357169.0
2014       312905.0  383477.0
2015       309794.0  413154.0
2016       172957.0  379789.0
2017       134726.0  330434.0
2018       141071.0  352879.0
2019       113722.0  341801.0
2020        64156.0  241877.0
2021        29974.0  215366.0

In [147]:
cv_crosstab['Total'] = cv_crosstab.loc[:, 0:].apply(np.sum, axis=1)

In [148]:
total = cv_crosstab.sum()
total.name = 'Total'
cv_crosstab = cv_crosstab.append(total.transpose())

## Converter de float para int32

In [149]:
cv_crosstab[[1]] = np.nan_to_num(cv_crosstab[[1]]).astype(int)
cv_crosstab[[0]] = np.nan_to_num(cv_crosstab[[0]]).astype(int)
cv_crosstab['Total'] = np.nan_to_num(cv_crosstab['Total']).astype(int)

## Crosstabs CV: anocoleta * PriCV

In [150]:
cv_crosstab2 =  tb_carga_viral_consolidado['anocoleta',"('PriCV',)" ]

In [151]:
cv_crosstab2 = cv_crosstab2.to_pandas_df(['anocoleta',"('PriCV',)"])

In [152]:
cv_crosstab2 = cv_crosstab2.groupby(['anocoleta',"('PriCV',)"]).size().reset_index(name='Total')

In [153]:
cv_crosstab2 = pd.pivot_table(cv_crosstab2, values='Total', index=['anocoleta'],
                    columns=["('PriCV',)"], aggfunc=np.sum)

In [154]:
cv_crosstab2['Total'] = cv_crosstab2.loc[:, 0:].apply(np.sum, axis=1)

In [155]:
total = cv_crosstab2.sum()
total.name = 'Total'
cv_crosstab2 = cv_crosstab2.append(total.transpose())

In [156]:
cv_crosstab2[[1]] = np.nan_to_num(cv_crosstab2[[1]]).astype(int)
cv_crosstab2[[0]] = np.nan_to_num(cv_crosstab2[[0]]).astype(int)
cv_crosstab2['Total'] = np.nan_to_num(cv_crosstab2['Total']).astype(int)

In [157]:
cv_crosstab2

('PriCV',)        0        1    Total
anocoleta
2000             40       85      125
2001            394     9785    10179
2002          53977    71162   125139
2003         133097    40419   173516
2004         191783    50119   241902
2005         278179    52716   330895
2006         348637    42785   391422
2007         395218    48096   443314
2008         445407    42661   488068
2009         483512    42491   526003
2010         506540    43120   549660
2011         544660    46247   590907
2012         573845    46412   620257
2013         613936    50244   664180
2014         642140    54242   696382
2015         663807    59141   722948
2016         491482    61264   552746
2017         403340    61820   465160
2018         429067    64883   493950
2019         390372    65151   455523
2020         254868    51165   306033
2021         207450    37890   245340
Total       8051751  1041898  9093649

## Salvar tabelas no arquivo excel: 1 Indicadores / sheet: Gerais

In [158]:
with pd.ExcelWriter('1 Indicadores Agosto2021.xlsx') as writer:  
    table_crosstab.to_excel(writer, sheet_name='Gerais Agosto2021', startcol=3 ,startrow= 72, index_label='anodisp/UltDispAno')
    table_crosstab2.to_excel(writer, sheet_name='Gerais Agosto2021', startcol=8 ,startrow= 72, index_label= 'anodisp/PriDisp')
    table_crosstab3.to_excel(writer, sheet_name='Gerais Agosto2021', startcol=13 ,startrow= 72, index_label= 'cod_pac_final/UltDispVida')
    cd4_crosstab5.to_excel(writer, sheet_name='Gerais Agosto2021', startcol=3 ,startrow= 3, index_label='cod_pac_final/CD4maispertoPriDisp_ano')
    cd4_crosstab.to_excel(writer, sheet_name='Gerais Agosto2021', startcol=3 ,startrow= 12, index_label= 'anocoleta/UltCD4Ano')
    cd4_crosstab3.to_excel(writer, sheet_name='Gerais Agosto2021', startcol=8 ,startrow= 12, index_label= 'anocoleta/priCD4_antesTARV')
    cd4_crosstab2.to_excel(writer, sheet_name='Gerais Agosto2021', startcol=13 ,startrow= 12, index_label= 'anocoleta/PriCD4')
    cv_crosstab.to_excel(writer, sheet_name='Gerais Agosto2021', startcol=3 ,startrow= 40, index_label= 'anocoleta/UltCVAno')
    cv_crosstab2.to_excel(writer, sheet_name='Gerais Agosto2021', startcol=8 ,startrow= 40, index_label= 'anocoleta/PriCV')

# Crosstabs - arquivo: 2 Indicadores TARV - sheet: (1) PriDisp&TARV  - Crosstabs CD4 - tabela: tb_dispensas_esquemas_udm.txt

In [159]:
tb_dispensas_esquemas_udm.info()

## Crosstabs: dtdisp_mes * PriDisp * anodisp

In [160]:
dispensa2_crosstab =  tb_dispensas_esquemas_udm['anodisp','dtdisp_mes','PriDisp']

In [161]:
dispensa2_crosstab

#           anodisp    dtdisp_mes    PriDisp
0           2018       06-2018       0
1           2018       03-2018       0
2           2018       09-2018       0
3           2018       10-2018       0
4           2018       11-2018       0
...         ...        ...           ...
16,599,047  2019       01-2019       0
16,599,048  2019       02-2019       0
16,599,049  2018       06-2018       0
16,599,050  2019       11-2019       0
16,599,051  2018       03-2018       0

In [162]:
dispensa2_crosstab = dispensa2_crosstab.to_pandas_df(['anodisp','dtdisp_mes','PriDisp'])

In [163]:
dispensa2_crosstab = dispensa2_crosstab.groupby(['anodisp','dtdisp_mes','PriDisp']).size().reset_index(name='Total')

In [164]:
dispensa2_crosstab = pd.pivot_table(dispensa2_crosstab, values='Total', index=['anodisp', 'dtdisp_mes'],
                    columns=[ 'PriDisp'], aggfunc=np.sum)

In [165]:
dispensa2_crosstab

PriDisp                  0     1
anodisp dtdisp_mes
2018    01-2018     400965  5769
        02-2018     368071  5152
        03-2018     398207  5927
        04-2018     425113  5959
        05-2018     424000  5852
        06-2018     411614  5454
        07-2018     430089  5518
        08-2018     443239  6182
        09-2018     385000  5590
        10-2018     439943  6620
        11-2018     412601  5408
        12-2018     374820  5158
2019    01-2019     402785  5723
        02-2019     396073  5874
        03-2019     378147  5209
        04-2019     412142  5901
        05-2019     418798  6167
        06-2019     375040  5154
        07-2019     421391  5956
        08-2019     406849  5914
        09-2019     392444  5607
        10-2019     413017  6143
        11-2019     389229  5575
        12-2019     373785  5109
2020    01-2020     419238  5621
        02-2020     380593  4924
        03-2020     479180  5808
        04-2020     363954  4194
        05-2020     284458  3604
        06-2020     305039  3901
        07-2020     314958  4378
        08-2020     296963  4344
        09-2020     309052  4630
        10-2020     307427  4603
        11-2020     309001  4560
        12-2020     318672  4504
2021    01-2021     295905  4091
        02-2021     297369  4413
        03-2021     348821  5434
        04-2021     321446  4741
        05-2021     333137  4874
        06-2021     328467  5034
        07-2021     329320  5168
        08-2021     331587  5356

## Soma das colunas da tabela dispensa2_crosstab

In [166]:
dispensa2_crosstab['Total'] = dispensa2_crosstab.loc[:, 0:].apply(np.sum, axis=1)

In [167]:
total = dispensa2_crosstab.sum()
total.name = 'Total'
dispensa2_crosstab = dispensa2_crosstab.append(total.transpose())

## Crosstabs: dtdisp_mes * UltDispAno * anodisp

In [168]:
tb_dispensas_esquemas_udm.info()

In [169]:
dispensa2_crosstab2 =  tb_dispensas_esquemas_udm['anodisp','dtdisp_mes','UltDispAno']

In [170]:
dispensa2_crosstab2 = dispensa2_crosstab2.to_pandas_df(['anodisp','dtdisp_mes','UltDispAno'])

In [171]:
dispensa2_crosstab2 = dispensa2_crosstab2.groupby(['anodisp','dtdisp_mes','UltDispAno']).size().reset_index(name='Total')

In [172]:
dispensa2_crosstab2 = pd.pivot_table(dispensa2_crosstab2, values='Total', index=['anodisp', 'dtdisp_mes'],
                    columns=[ 'UltDispAno'], aggfunc=np.sum)

In [173]:
dispensa2_crosstab2['Total'] = dispensa2_crosstab2.loc[:, 0:].apply(np.sum, axis=1)

In [174]:
total = dispensa2_crosstab2.sum()
total.name = 'Total'
dispensa2_crosstab2 = dispensa2_crosstab2.append(total.transpose())

In [175]:
dispensa2_crosstab2

UltDispAno              0        1     Total
(2018, 01-2018)    403330     3404    406734
(2018, 02-2018)    370157     3066    373223
(2018, 03-2018)    400484     3650    404134
(2018, 04-2018)    426870     4202    431072
(2018, 05-2018)    425236     4616    429852
(2018, 06-2018)    412086     4982    417068
(2018, 07-2018)    428855     6752    435607
(2018, 08-2018)    438790    10631    449421
(2018, 09-2018)    374571    16019    390590
(2018, 10-2018)    392741    53822    446563
(2018, 11-2018)    251337   166672    418009
(2018, 12-2018)     12206   367772    379978
(2019, 01-2019)    405049     3459    408508
(2019, 02-2019)    398471     3476    401947
(2019, 03-2019)    379587     3769    383356
(2019, 04-2019)    413721     4322    418043
(2019, 05-2019)    419696     5269    424965
(2019, 06-2019)    374759     5435    380194
(2019, 07-2019)    419110     8237    427347
(2019, 08-2019)    400120    12643    412763
(2019, 09-2019)    374167    23884    398051
(2019, 10-2019)    342947    76213    419160
(2019, 11-2019)    211731   183073    394804
(2019, 12-2019)     13079   365815    378894
(2020, 01-2020)    420845     4014    424859
(2020, 02-2020)    381722     3795    385517
(2020, 03-2020)    478879     6109    484988
(2020, 04-2020)    362637     5511    368148
(2020, 05-2020)    282257     5805    288062
(2020, 06-2020)    301347     7593    308940
(2020, 07-2020)    307715    11621    319336
(2020, 08-2020)    284476    16831    301307
(2020, 09-2020)    276310    37372    313682
(2020, 10-2020)    205471   106559    312030
(2020, 11-2020)    103863   209698    313561
(2020, 12-2020)      9836   313340    323176
(2021, 01-2021)    294551     5445    299996
(2021, 02-2021)    294921     6861    301782
(2021, 03-2021)    342933    11322    354255
(2021, 04-2021)    309805    16382    326187
(2021, 05-2021)    299001    39010    338011
(2021, 06-2021)    219314   114187    333501
(2021, 07-2021)    118609   215879    334488
(2021, 08-2021)     10250   326693    336943
Total            13793842  2805210  16599052

# Crosstabs : anodisp*PriDisp*UF / anodisp*UltDispAno*UF/ mes*PriDisp*UF

## Variável UF do banco de pacientes - arquivo: paciente_mar2021_unico.txt

In [181]:
paciente_mar2021_unico = pd.read_csv("C:/Users/lemos/Downloads/AMA/produtos_opas/2021/produto2/dispensa/paciente_mar2021_unico.txt", 
                       sep='\t',
                       error_bad_lines=False)

C:\Users\lemos\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3331: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\lemos\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3331: DtypeWarning: Columns (1,7,10) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [183]:
paciente_mar2021_unico.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1400917 entries, 0 to 1400916
Data columns (total 20 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   Unnamed: 0         1400917 non-null  int64
 1   cod_pac_final      1400917 non-null  object
 2   data_nascimento    1396164 non-null  object
 3   sexo               1358335 non-null  float64
 4   raca               1400917 non-null  float64
 5   estado_civil       540271 non-null   float64
 6   codigo_ibge_resid  1361786 non-null  float64
 7   codigo_ibge_nasc   1363600 non-null  object
 8   uf_nasc            1363372 non-null  object
 9   escolaridade       1113264 non-null  float64
 10  caso_aids          657657 non-null   object
 11  st_trans           1400917 non-null  int64
 12  st_prep            1400917 non-null  int64
 13  st_pais            1269184 non-null  float64
 14  regiao             1400917 non-null  object
 15  UF                 1400917 non-null  object
 16  codmun_resid       1361786 non-null  float64
 17  escol4             1400917 non-null  float64
 18  escol3             1400917 non-null  float64
 19  raca3_cat          1400917 non-null  float64
dtypes: float64(10), int64(3), object(7)
memory usage: 213.8+ MB

In [186]:
UF_paciente =  paciente_mar2021_unico[['cod_pac_final', 'UF']]

In [187]:
UF_paciente

        cod_pac_final  UF
0                      52
1            00000001  33
2            00000002  33
3            00000003  33
4            00000004  33
...               ...  ..
1400912      99999995  35
1400913      99999996  35
1400914      99999997  33
1400915      99999998  35
1400916      99999999  43

[1400917 rows x 2 columns]

In [190]:
tb_dispensas_esquemas_udm.info()

In [231]:
dispensa_pridisp_cod_pac = tb_dispensas_esquemas_udm[['codigo_paciente', 'PriDisp', 'UltDispAno', 'dtdisp_mes', 'anodisp']]

In [232]:
dispensa_pridisp_cod_pac = dispensa_pridisp_cod_pac.to_pandas_df(['codigo_paciente', 'PriDisp', 'UltDispAno', 'dtdisp_mes', 'anodisp'])

In [233]:
dispensa_pridisp_cod_pac = dispensa_pridisp_cod_pac.rename(columns={"codigo_paciente": "cod_pac_final"})

In [234]:
tb_dispensas_esquemas_udm_paciente_uf_merged = pd.merge(dispensa_pridisp_cod_pac, UF_paciente)

In [235]:
tb_dispensas_esquemas_udm_paciente_uf_merged

         cod_pac_final  PriDisp  UltDispAno dtdisp_mes anodisp  UF
0                   70        0           0    06-2018    2018  33
1                   70        0           0    03-2018    2018  33
2                   70        0           1    11-2019    2019  33
3                   70        0           0    03-2021    2021  33
4                   70        0           0    09-2018    2018  33
...                ...      ...         ...        ...     ...  ..
14866551          6736        0           0    01-2021    2021  33
14866552          6736        0           0    01-2019    2019  33
14866553          6736        0           0    02-2019    2019  33
14866554          6736        0           0    06-2018    2018  33
14866555          6736        0           1    11-2019    2019  33

[14866556 rows x 6 columns]

## anodisp*PriDisp*UF

In [215]:
cross_dispensa_paciente_merged = tb_dispensas_esquemas_udm_paciente_uf_merged.groupby([ 'UF','anodisp', 'PriDisp' ]).size().reset_index(name='Total')

In [216]:
cross_dispensa_paciente_merged = pd.pivot_table(cross_dispensa_paciente_merged, values='Total', index=['UF', 'PriDisp'],
                    columns=[ 'anodisp'], aggfunc=np.sum)

In [224]:
cross_dispensa_paciente_merged

anodisp     2018     2019     2020     2021     Total
(11, 0)    25780    25176    22141    15346     88443
(11, 1)      509      549      457      159      1674
(12, 0)     4425     4032     4234     2586     15277
(12, 1)      140      139      107       43       429
(13, 0)    95736    74629    67225    38897    276487
(13, 1)     2141     2281     1717      503      6642
(14, 0)     5936     6561     7387     5369     25253
(14, 1)      348      367      243      138      1096
(15, 0)   124713   114623   113043    69678    422057
(15, 1)     3139     3285     2722      790      9936
(16, 0)     6731     7456     7833     5055     27075
(16, 1)      310      330      221       71       932
(17, 0)    10024    10819    10649     7211     38703
(17, 1)      413      293      260       98      1064
(21, 0)    88480    91227    78698    50803    309208
(21, 1)     2083     1932     1572      488      6075
(22, 0)    25768    23604    22758    14539     86669
(22, 1)      696      802      612      172      2282
(23, 0)   110918   108228    95496    60928    375570
(23, 1)     2678     3147     2189      630      8644
(24, 0)    55555    62239    43593    21400    182787
(24, 1)     1077      938      794      250      3059
(25, 0)    49030    52907    41444    28730    172111
(25, 1)      785      853      614      196      2448
(26, 0)   182269   203594   160097   100296    646256
(26, 1)     3130     3166     2261      744      9301
(27, 0)    34337    31477    28345    18992    113151
(27, 1)      954      986      698      312      2950
(28, 0)    24038    20864    17784    12001     74687
(28, 1)      570      574      401      112      1657
(29, 0)   199782   206198   172108   113910    691998
(29, 1)     3245     3336     2597      767      9945
(31, 0)   364963   353768   292650   166379   1177760
(31, 1)     4724     4484     3753     1171     14132
(32, 0)    76300    75412    67120    42991    261823
(32, 1)     1299     1292     1040      283      3914
(33, 0)   636765   637635   509218   325942   2109560
(33, 1)     7495     6772     5576     1754     21597
(35, 0)   972631   918087   827907   518105   3236730
(35, 1)    13004    12325    10225     3180     38734
(41, 0)   237113   217913   193123   118575    766724
(41, 1)     3622     3529     2523      819     10493
(42, 0)   265625   261329   232963   143373    903290
(42, 1)     3541     3404     2687      880     10512
(43, 0)   522565   533045   432835   281168   1769613
(43, 1)     5362     5259     4224     1385     16230
(50, 0)    46475    47219    44418    28365    166477
(50, 1)      992      979      826      253      3050
(51, 0)    63968    57453    52023    33090    206534
(51, 1)     1205     1323     1021      328      3877
(52, 0)    85160    75498    78370    50817    289845
(52, 1)     1984     2005     1805      578      6372
(53, 0)    62252    55411    52320    29704    199687
(53, 1)      941      899      866      291      2997
(na, 0)     8480     8995     8461     5735     31671
(na, 1)      211      373      204      280      1068
Total    4452417  4351021  3736458  2326660  14866556

In [221]:
cross_dispensa_paciente_merged['Total'] = cross_dispensa_paciente_merged.loc[:, :].apply(np.sum, axis=1)

In [223]:
total = cross_dispensa_paciente_merged.sum()
total.name = 'Total'
cross_dispensa_paciente_merged = cross_dispensa_paciente_merged.append(total.transpose())

## anodisp*UltDispAno*UF

In [225]:
cross_dispensa_paciente_merged2 = tb_dispensas_esquemas_udm_paciente_uf_merged.groupby([ 'UF','anodisp', 'UltDispAno' ]).size().reset_index(name='Total')

In [226]:
cross_dispensa_paciente_merged2 = pd.pivot_table(cross_dispensa_paciente_merged2, values='Total', index=['UF', 'UltDispAno'],
                    columns=[ 'anodisp'], aggfunc=np.sum)

In [230]:
cross_dispensa_paciente_merged2

anodisp     2018     2019     2020     2021     Total
(11, 0)    22462    21475    18029    11062     73028
(11, 1)     3827     4250     4569     4443     17089
(12, 0)     3710     3203     3334     1614     11861
(12, 1)      855      968     1007     1015      3845
(13, 0)    85044    62287    53339    24299    224969
(13, 1)    12833    14623    15603    15101     58160
(14, 0)     4649     5036     5631     3538     18854
(14, 1)     1635     1892     1999     1969      7495
(15, 0)   108504    96200    92427    47778    344909
(15, 1)    19348    21708    23338    22690     87084
(16, 0)     5192     5682     5846     3002     19722
(16, 1)     1849     2104     2208     2124      8285
(17, 0)     8051     8502     8142     4595     29290
(17, 1)     2386     2610     2767     2714     10477
(21, 0)    77821    79064    65268    36784    258937
(21, 1)    12742    14095    15002    14507     56346
(22, 0)    21684    18975    17602     9106     67367
(22, 1)     4780     5431     5768     5605     21584
(23, 0)    96781    91853    76710    41083    306427
(23, 1)    16815    19522    20975    20475     77787
(24, 0)    50125    55856    36534    13965    156480
(24, 1)     6507     7321     7853     7685     29366
(25, 0)    43544    46807    34764    21811    146926
(25, 1)     6271     6953     7294     7115     27633
(26, 0)   163774   182654   136927    76165    559520
(26, 1)    21625    24106    25431    24875     96037
(27, 0)    29356    25763    21954    12349     89422
(27, 1)     5935     6700     7089     6955     26679
(28, 0)    20747    17148    13664     7739     59298
(28, 1)     3861     4290     4521     4374     17046
(29, 0)   180211   184069   147664    88217    600161
(29, 1)    22816    25465    27041    26460    101782
(31, 0)   325935   311230   246825   118755   1002745
(31, 1)    43752    47022    49578    48795    189147
(32, 0)    66314    64507    55309    30799    216929
(32, 1)    11285    12197    12851    12475     48808
(33, 0)   570684   566670   434324   249290   1820968
(33, 1)    73576    77737    80470    78406    310189
(35, 0)   844044   780233   681831   368083   2674191
(35, 1)   141591   150179   156301   153202    601273
(41, 0)   209396   187346   160054    84423    641219
(41, 1)    31339    34096    35592    34971    135998
(42, 0)   234480   227447   196608   106078    764613
(42, 1)    34686    37286    39042    38175    149189
(43, 0)   469560   476266   372804   219660   1538290
(43, 1)    58367    62038    64255    62893    247553
(50, 0)    41483    41456    37940    21387    142266
(50, 1)     5984     6742     7304     7231     27261
(51, 0)    56028    48612    42115    22678    169433
(51, 1)     9145    10164    10929    10740     40978
(52, 0)    71491    60284    61612    33110    226497
(52, 1)    15653    17219    18563    18285     69720
(53, 0)    53553    45956    42256    19127    160892
(53, 1)     9640    10354    10930    10868     41792
(na, 0)     7511     7924     7129     4295     26859
(na, 1)     1180     1444     1536     1720      5880
Total    4452417  4351021  3736458  2326660  14866556

In [228]:
cross_dispensa_paciente_merged2['Total'] = cross_dispensa_paciente_merged2.loc[:, :].apply(np.sum, axis=1)

In [229]:
total = cross_dispensa_paciente_merged2.sum()
total.name = 'Total'
cross_dispensa_paciente_merged2 = cross_dispensa_paciente_merged2.append(total.transpose())

## dtdisp_mes*PriDisp*UF

In [236]:
cross_dispensa_paciente_merged3 = tb_dispensas_esquemas_udm_paciente_uf_merged.groupby([ 'UF','dtdisp_mes' ]).size().reset_index(name='Total')

In [237]:
cross_dispensa_paciente_merged3 = pd.pivot_table(cross_dispensa_paciente_merged3, values='Total', index=['UF'],
                    columns=[ 'dtdisp_mes'], aggfunc=np.sum)

In [241]:
cross_dispensa_paciente_merged3

dtdisp_mes,01-2018,01-2019,01-2020,01-2021,02-2018,02-2019,02-2020,02-2021,03-2018,03-2019,...,10-2018,10-2019,10-2020,11-2018,11-2019,11-2020,12-2018,12-2019,12-2020,Total
UF,,,,,,,,,,,,,,,,,,,,,
11,2156,1970,2227,1753,2129,2056,2047,1832,1991,2150,...,2338,2221,1712,2223,2216,1824,1976,1861,1932,90117
12,347,353,409,302,340,329,338,280,388,305,...,428,364,342,338,368,263,266,323,294,15706
13,8035,7354,7997,5064,7305,6621,7466,4319,7770,6577,...,9316,5870,5250,8249,5975,4424,7005,6059,5165,283129
14,425,523,614,665,523,645,678,759,523,504,...,623,641,703,575,631,715,467,572,693,26349
15,10867,10762,11280,8133,9203,10332,9729,8175,11561,9816,...,10623,10001,8660,10690,9355,8868,8854,8798,8345,431993
16,648,630,683,618,573,605,628,618,569,559,...,647,643,671,574,683,602,611,667,673,28007
17,765,745,936,871,852,1012,935,809,819,860,...,953,957,954,900,1027,843,868,932,862,39767
21,7657,7623,8470,6954,6785,7433,7516,5868,7113,7422,...,8347,8151,6477,7452,8017,6317,6909,6809,6472,315283
22,1859,2129,2120,1738,1543,1975,1787,1784,1700,1914,...,2307,2151,1723,2103,2089,1926,1645,1894,1793,88951
23,9881,9138,10709,7888,8558,8951,9288,7741,10102,8211,...,9681,10008,7742,9000,9236,7621,8277,9176,7664,384214
24,4613,5356,5573,2317,4163,4907,5021,2726,4527,4837,...,5190,5686,2437,5037,5184,2889,4801,5397,2470,185846
25,3762,4037,4636,2920,3769,4055,4457,3723,4114,4185,...,4684,4890,3796,4395,4571,2989,3992,4707,3825,174559
26,14977,17573,19155,11599,13652,16752,15589,12144,13289,15668,...,17539,18057,12985,16255,17103,12505,15676,16510,13850,655557
27,3108,2589,3060,2013,2705,2561,2617,2186,3069,2561,...,3170,3157,2098,2730,2706,2150,2706,2563,2584,116101
28,2160,1937,1938,1391,1655,1728,1647,1291,1903,1543,...,2084,1875,1482,1772,1787,1256,1492,1750,1352,76344
29,17054,17192,19352,13139,14275,17563,16483,14962,15931,16337,...,18938,18262,14508,17718,17147,13954,16285,17135,16077,701943
31,31409,29183,32322,19873,27666,29809,28120,19772,29693,27598,...,31585,31782,20431,32938,29574,21820,27894,28402,20423,1191892
32,6457,6268,6819,5064,5667,6215,6454,4663,6225,5844,...,6899,6869,5062,6349,6157,5674,5957,6517,5287,265737
33,53832,57315,56649,37647,46860,55283,49121,38482,51362,51372,...,59000,55298,39173,54882,51101,37715,51570,49590,42751,2131157
35,78793,79494,81955,60535,75101,77522,74738,61410,82252,74340,...,86887,79552,63391,79946,75601,64048,72116,71680,65123,3275464
41,17600,17060,17435,13156,17564,18411,18328,13875,19204,17248,...,22393,19593,14808,20566,18041,15280,17937,16829,14342,777217
42,19678,19516,22117,15506,20657,21595,22851,17636,21779,20214,...,24788,23847,17892,22956,22829,18035,20468,20775,17367,913802
43,43805,45875,43012,34150,38835,42903,41911,29909,41187,43415,...,48287,45264,31254,45141,42863,33718,42833,42851,33567,1785843
50,3476,3780,4102,3271,3517,3865,3946,3402,3772,3812,...,4280,4313,3514,4074,4024,3655,3868,3766,3522,169527
51,5396,4685,5299,4013,5352,4663,4984,4213,5563,4539,...,5189,5063,4362,5058,5085,3806,4231,4714,4083,210411
52,7162,6920,7245,6146,7625,6547,5911,5909,8044,6159,...,7342,6599,5702,6949,6424,5827,6330,5799,6104,296217
53,5334,5576,5532,3384,4802,5005,4175,3158,5615,5093,...,5679,4726,3585,5042,4283,3294,4767,4124,4584,202684
na,713,741,916,571,624,756,842,630,673,708,...,803,860,678,737,820,591,673,748,698,32739

In [240]:
cross_dispensa_paciente_merged3['Total'] = cross_dispensa_paciente_merged3.loc[:,:].apply(np.sum, axis=1)

In [242]:
total = cross_dispensa_paciente_merged3.sum()
total.name = 'Total'
cross_dispensa_paciente_merged3 = cross_dispensa_paciente_merged3.append(total.transpose())

In [243]:
cross_dispensa_paciente_merged3

dtdisp_mes,01-2018,01-2019,01-2020,01-2021,02-2018,02-2019,02-2020,02-2021,03-2018,03-2019,...,10-2018,10-2019,10-2020,11-2018,11-2019,11-2020,12-2018,12-2019,12-2020,Total
UF,,,,,,,,,,,,,,,,,,,,,
11,2156,1970,2227,1753,2129,2056,2047,1832,1991,2150,...,2338,2221,1712,2223,2216,1824,1976,1861,1932,90117
12,347,353,409,302,340,329,338,280,388,305,...,428,364,342,338,368,263,266,323,294,15706
13,8035,7354,7997,5064,7305,6621,7466,4319,7770,6577,...,9316,5870,5250,8249,5975,4424,7005,6059,5165,283129
14,425,523,614,665,523,645,678,759,523,504,...,623,641,703,575,631,715,467,572,693,26349
15,10867,10762,11280,8133,9203,10332,9729,8175,11561,9816,...,10623,10001,8660,10690,9355,8868,8854,8798,8345,431993
16,648,630,683,618,573,605,628,618,569,559,...,647,643,671,574,683,602,611,667,673,28007
17,765,745,936,871,852,1012,935,809,819,860,...,953,957,954,900,1027,843,868,932,862,39767
21,7657,7623,8470,6954,6785,7433,7516,5868,7113,7422,...,8347,8151,6477,7452,8017,6317,6909,6809,6472,315283
22,1859,2129,2120,1738,1543,1975,1787,1784,1700,1914,...,2307,2151,1723,2103,2089,1926,1645,1894,1793,88951
23,9881,9138,10709,7888,8558,8951,9288,7741,10102,8211,...,9681,10008,7742,9000,9236,7621,8277,9176,7664,384214
24,4613,5356,5573,2317,4163,4907,5021,2726,4527,4837,...,5190,5686,2437,5037,5184,2889,4801,5397,2470,185846
25,3762,4037,4636,2920,3769,4055,4457,3723,4114,4185,...,4684,4890,3796,4395,4571,2989,3992,4707,3825,174559
26,14977,17573,19155,11599,13652,16752,15589,12144,13289,15668,...,17539,18057,12985,16255,17103,12505,15676,16510,13850,655557
27,3108,2589,3060,2013,2705,2561,2617,2186,3069,2561,...,3170,3157,2098,2730,2706,2150,2706,2563,2584,116101
28,2160,1937,1938,1391,1655,1728,1647,1291,1903,1543,...,2084,1875,1482,1772,1787,1256,1492,1750,1352,76344
29,17054,17192,19352,13139,14275,17563,16483,14962,15931,16337,...,18938,18262,14508,17718,17147,13954,16285,17135,16077,701943
31,31409,29183,32322,19873,27666,29809,28120,19772,29693,27598,...,31585,31782,20431,32938,29574,21820,27894,28402,20423,1191892
32,6457,6268,6819,5064,5667,6215,6454,4663,6225,5844,...,6899,6869,5062,6349,6157,5674,5957,6517,5287,265737
33,53832,57315,56649,37647,46860,55283,49121,38482,51362,51372,...,59000,55298,39173,54882,51101,37715,51570,49590,42751,2131157
35,78793,79494,81955,60535,75101,77522,74738,61410,82252,74340,...,86887,79552,63391,79946,75601,64048,72116,71680,65123,3275464
41,17600,17060,17435,13156,17564,18411,18328,13875,19204,17248,...,22393,19593,14808,20566,18041,15280,17937,16829,14342,777217
42,19678,19516,22117,15506,20657,21595,22851,17636,21779,20214,...,24788,23847,17892,22956,22829,18035,20468,20775,17367,913802
43,43805,45875,43012,34150,38835,42903,41911,29909,41187,43415,...,48287,45264,31254,45141,42863,33718,42833,42851,33567,1785843
50,3476,3780,4102,3271,3517,3865,3946,3402,3772,3812,...,4280,4313,3514,4074,4024,3655,3868,3766,3522,169527
51,5396,4685,5299,4013,5352,4663,4984,4213,5563,4539,...,5189,5063,4362,5058,5085,3806,4231,4714,4083,210411
52,7162,6920,7245,6146,7625,6547,5911,5909,8044,6159,...,7342,6599,5702,6949,6424,5827,6330,5799,6104,296217
53,5334,5576,5532,3384,4802,5005,4175,3158,5615,5093,...,5679,4726,3585,5042,4283,3294,4767,4124,4584,202684
na,713,741,916,571,624,756,842,630,673,708,...,803,860,678,737,820,591,673,748,698,32739
Total,361969,366324,382562,270681,332300,360099,347607,272276,360738,343791,...,400000,376700,281392,374649,354897,282609,340474,340948,291902,14866556

## Salvar Arquivo: 2 Indicadores TARV - Sheet: (1) PriDisp&TARV

In [244]:
with pd.ExcelWriter('2 Indicadores Agosto2021_TARV.xlsx') as writer:  
    dispensa2_crosstab.to_excel(writer, sheet_name='(1) PriDisp&TARV Agosto2021', startcol=3 ,startrow= 3, index_label= 'anodisp/dtdisp_mes/PriDisp')
    table_crosstab2.to_excel(writer, sheet_name='(1) PriDisp&TARV Agosto2021', startcol=8 ,startrow= 3, index_label= 'anodisp/PriDisp')
    dispensa2_crosstab2.to_excel(writer, sheet_name='(1a) UltDispAnoMes Agosto2021', startcol=3 ,startrow= 3, index_label= 'anodisp/dtdisp_mes/UltDispAno')
    cross_dispensa_paciente_merged.to_excel(writer, sheet_name='(2) PriDisp UF Agosto2021', startcol=3 ,startrow= 3, index_label= 'UF/PriDisp/anodisp')
    cross_dispensa_paciente_merged2.to_excel(writer, sheet_name='(3) UltDispAno UF Agosto2021', startcol=3 ,startrow= 3, index_label= 'UF/UltDispAno/anodisp')
    cross_dispensa_paciente_merged3.to_excel(writer, sheet_name='(4) PriDisp Mês UF Agosto2021', startcol=3 ,startrow= 3, index_label= 'UF/PriDisp/dtmes_disp')